# **Data Preparation**

Tomando como base el archivo "base supermercado", analizaremos cada tabla, corregiremos errores y transformaremos aplicando las 3 formas normales.

##Importamos librerías y la Base de Datos de Supermercado

In [ ]:
from google.colab import files
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

Librerías que vamos a utilizar

In [ ]:
import pandas as pd
import datetime as datetime
import numpy as np

#Tabla Maestro Sucursales:

Contiene 433 registros de sucursales, y 15 columnas de datos.

Columna  | Nombre  | Descripción
----------  | ---------|------------------
0  | idSucursal       | contiene datos int, PK de la tabla
1	|fechaAlta       | datetime, sin nulos, fecha de alta de cada sucursal
2	|nombre       | nombre de cada sucursal, contiene un nulo, string
3	|direccion       |  calle y número en algunos, contiene algunos nulos, string
4	|localidad       | string, contiene nulos, ciudad de la sucursal
5	|provincia       | string, contiene nulos, ciudad de la sucursal
6	|horarioLunes       | rango horario del día de la sucursal
7	|horarioMartes       | rango horario del día de la sucursal
8	|horarioMiercoles       | rango horario del día de la sucursal
9	|horarioJueves       | rango horario del día de la sucursal
10	|horarioViernes       | rango horario del día de la sucursal
11	|horarioSabado       | rango horario del día de la sucursal
12	|horarioDomingo       | rango horario del día de la sucursal
13	|fechaBaja       | fecha de baja de la sucursal, sin dato
14	|estado       | estado de la sucursal, sin dato

##Importar tabla

In [ ]:
bs_maestro_suc = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='Maestro SUCURSALES')
bs_maestro_suc.shape

(433, 15)

In [ ]:
bs_maestro_suc.head()

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
0,1,2000-01-12,LIBERTOR GRAL SAN MARTIN,AV. LIBERTAD 569,S S JUJUY,JUJUY,08:00-21:00,07:00-21:00,07:00-21:00,07:00-21:00,07:00-21:00,10:00-20:00,10:00-20:00,NaN,NaN
1,2,2000-01-14,CRUZ DEL EJE,RIVADAVIA 197,CORDOBA,CORDOBA,08:00-21:00,08:00-21:00,07:00-22:00,07:00-22:00,07:00-21:00,08:00-21:00,08:00-21:00,NaN,NaN
2,3,2000-03-01,AV CORONEL DIAZ,AV. SANTA FE,PALERMO,CAPITAL FEDERAL,07:00-22:00,07:00-21:00,07:00-22:00,08:00-21:00,07:00-22:00,10:00-20:00,10:00-14:00,NaN,NaN
3,4,2000-03-04,LANUS ESTE,AV. 9 DE JULIO 1472,LANUS,BUENOS AIRES,07:00-22:00,07:00-22:00,08:00-21:00,07:00-22:00,07:00-22:00,08:00-21:00,08:00-21:00,NaN,NaN
4,5,2000-04-09,ZARATE,19 DE MARZO 234,ZARATE,BUENOS AIRES,08:00-21:00,07:00-21:00,08:00-21:00,08:00-21:00,07:00-22:00,10:00-20:00,09:00-21:00,NaN,NaN

In [ ]:
bs_maestro_suc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433 entries, 0 to 432
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   idSucursal        433 non-null    int64
 1   fechaAlta         433 non-null    datetime64[ns]
 2   nombre            432 non-null    object
 3   direccion         431 non-null    object
 4   localidad         432 non-null    object
 5   provincia         432 non-null    object
 6   horarioLunes      433 non-null    object
 7   horarioMartes     433 non-null    object
 8   horarioMiercoles  433 non-null    object
 9   horarioJueves     433 non-null    object
 10  horarioViernes    433 non-null    object
 11  horarioSabado     433 non-null    object
 12  horarioDomingo    433 non-null    object
 13  fechaBaja         0 non-null      float64
 14  estado            0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(11)
memory usage: 50.9+ KB

##Control de Maestro Sucursales

###Campo idSucursales

In [ ]:
bs_maestro_suc['idSucursal'].value_counts()

idSucursal
1      1
286    1
297    1
296    1
295    1
      ..
142    1
141    1
140    1
139    1
433    1
Name: count, Length: 433, dtype: int64

Contando los valores de idSucursal comprobamos que ninguno se repite, falta verificar que los valores sean entre 1 y 433.

In [ ]:
ls_idsuc = bs_maestro_suc['idSucursal'] #convertimos en lista los idSucursal

id_sucursalesfiltradas = [num for num in ls_idsuc if 1 <= num <= 433]
id_sucursalesfiltradas_n = [num for num in ls_idsuc if 1 > num > 433]

print("Números dentro del rango:", id_sucursalesfiltradas)
print("Números fuera del rango:", id_sucursalesfiltradas_n)

Números dentro del rango: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433]
Números fuera del rango: []

Ninguno de los números de idSucursal esta fuera del rango, ni repetido, pueden ser utilizados como PK

###Campo Fecha Alta

In [ ]:
bs_maestro_suc['fechaAlta'].head()

0   2000-01-12
1   2000-01-14
2   2000-03-01
3   2000-03-04
4   2000-04-09
Name: fechaAlta, dtype: datetime64[ns]

Las fechas estan en formato  datetime64[ns], donde podrían también tener cargada la hora, para el análisis no es significativo.

In [ ]:
años = bs_maestro_suc['fechaAlta'].dt.year
años.value_counts()

fechaAlta
2012    52
2010    47
2011    45
2013    37
2014    36
2002    24
2009    21
2008    20
2006    19
2007    19
2003    18
2015    18
2001    18
2000    17
2004    16
2016    14
2005    12
Name: count, dtype: int64

Este paso nos muestra la cantidad de sucursales por año de alta, no hay evidencia de errores con las fechas de altas.

###Campo Nombre

In [ ]:
bs_maestro_suc['nombre'].head()

0    LIBERTOR GRAL SAN MARTIN
1                CRUZ DEL EJE
2             AV CORONEL DIAZ
3                  LANUS ESTE
4                      ZARATE
Name: nombre, dtype: object

In [ ]:
 bs_maestro_suc[bs_maestro_suc['nombre'].isna()]

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
234,235,2011-02-28,NaN,NaN,NaN,NaN,08:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,Cerrado,Cerrado,NaN,NaN

La sucursal con id 235 no tenemos datos de nombre, dirección, localidad ni provincia, solo los horarios de apertura

In [ ]:
bs_maestro_suc[(bs_maestro_suc['idSucursal']>225) & (bs_maestro_suc['idSucursal']<245)]

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
225,226,2010-11-15,JOSE LEÓN SUAREZ,JUAN MANUEL DE ROSAS 2435,JOSE LEON SUAREZ,BUENOS AIRES,08:00-21:00,07:00-22:00,08:00-21:00,08:00-21:00,08:00-21:00,10:00-20:00,10:00-20:00,NaN,NaN
226,227,2010-11-29,TORCUATO PANAMERICANA,RIOBAMBA N 1515 ESQUINA ANGEL ALVEAR,DON TORCUATO,BUENOS AIRES,07:00-21:00,08:00-21:00,08:00-21:00,07:00-22:00,07:00-21:00,Cerrado,Cerrado,NaN,NaN
227,228,2010-12-02,CENTRO VILLA MERCEDES,COLON,VILLA MERCEDES,SAN LUIS,07:00-22:00,07:00-21:00,07:00-22:00,08:00-21:00,07:00-22:00,10:00-20:00,08:00-21:00,NaN,NaN
228,229,2010-12-07,CAMPANA,ING. A.ROCCA 71,CAMPANA,BUENOS AIRES,07:00-22:00,07:00-22:00,07:00-21:00,07:00-21:00,07:00-21:00,Cerrado,08:00-21:00,NaN,NaN
229,230,2010-12-16,ALTA GRACIA,PADRE GRENON 207 ESQ. ARTURO ILLIA,ALTA GRACIA,CORDOBA,07:00-22:00,07:00-22:00,07:00-22:00,07:00-22:00,07:00-21:00,10:00-20:00,10:00-14:00,NaN,NaN
230,231,2010-12-25,GRAL. SAN MARTÍN - MENDOZA,AV. BOULOGNE SUR MER 150,GRAL. SAN MARTIN,MENDOZA,08:00-21:00,07:00-21:00,08:00-21:00,07:00-22:00,07:00-22:00,10:00-20:00,10:00-20:00,NaN,NaN
231,232,2011-01-15,MATADEROS,AV. J.B.ALBERDI 6367,MATADEROS,CAPITAL FEDERAL,07:00-21:00,08:00-21:00,08:00-21:00,07:00-22:00,07:00-22:00,10:00-14:00,08:00-21:00,NaN,NaN
232,233,2011-01-18,CALCHAQUÍ,AV. CALCHAQUI 1602,QUILMES,BUENOS AIRES,08:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,08:00-21:00,09:00-21:00,NaN,NaN
233,234,2011-02-23,ROSARIO - AV. PELLEGRINI,AV. CARLOS PELLEGRINI 1863,ROSARIO,SANTA FE,07:00-21:00,07:00-21:00,07:00-21:00,07:00-22:00,08:00-21:00,10:00-20:00,10:00-20:00,NaN,NaN
234,235,2011-02-28,NaN,NaN,NaN,NaN,08:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,Cerrado,Cerrado,NaN,NaN
235,236,2011-03-03,MENDOZA - SAN RAFAEL,DR. CARLOS PELLEGRINI 270,SAN RAFAEL,MENDOZA,07:00-22:00,07:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,08:00-21:00,10:00-14:00,NaN,NaN
236,237,2011-03-05,CENTRO PORTEÑO,MAIP 440,MICROCENTRO,CAPITAL FEDERAL,08:00-21:00,08:00-21:00,08:00-21:00,08:00-21:00,08:00-21:00,08:00-21:00,08:00-21:00,NaN,NaN
237,238,2011-03-07,AV. CABILDO,AV. CABILDO 1741,BELGRANO,CAPITAL FEDERAL,07:00-21:00,08:00-21:00,07:00-22:00,08:00-21:00,07:00-22:00,Cerrado,09:00-21:00,NaN,NaN
238,239,2011-03-15,BV M.T ALVEAR NEUQUEN,M.T. ALVEAR,NEUQUEN,NEUQUEN,08:00-21:00,07:00-22:00,07:00-21:00,07:00-22:00,08:00-21:00,09:00-21:00,10:00-14:00,NaN,NaN
239,240,2011-03-24,S. DEL ESTERO - AV. BELGRANO,AV. BELGRANO SUR 1987,SGTO DEL ESTERO,SANTIAGO DEL ESTERO,07:00-21:00,07:00-22:00,07:00-22:00,07:00-22:00,07:00-21:00,08:00-21:00,08:00-21:00,NaN,NaN
240,241,2011-03-25,OFICINA DIGITAL RECOLETA,AV. GELLY Y OBES 2206,RECOLETA,CAPITAL FEDERAL,07:00-22:00,08:00-21:00,08:00-21:00,07:00-21:00,07:00-22:00,10:00-20:00,09:00-21:00,NaN,NaN
241,242,2011-03-26,BELGRANO,AV. CABILDO 2491 2499,BELGRANO,CAPITAL FEDERAL,07:00-21:00,07:00-21:00,08:00-21:00,07:00-21:00,08:00-21:00,08:00-21:00,10:00-14:00,NaN,NaN
242,243,2011-04-01,TORTUGAS MALL,PANAMERICANA RAMAL PILAR KILMETRO 35.5.,GARIN,BUENOS AIRES,08:00-21:00,07:00-21:00,07:00-22:00,08:00-21:00,07:00-21:00,10:00-20:00,Cerrado,NaN,NaN
243,244,2011-04-25,PASEO DEL SIGLO,CORDOBA 1669,BELGRANO,SANTA FE,07:00-22:00,07:00-22:00,07:00-21:00,07:00-22:00,07:00-21:00,09:00-21:00,08:00-21:00,NaN,NaN

No hay un orden de idSucursal para poder asignarle un nombre a la sucursal y estimar una dirección.

### Campo Dirección

In [ ]:
bs_maestro_suc['direccion'].head()

0       AV. LIBERTAD 569
1          RIVADAVIA 197
2           AV. SANTA FE
3    AV. 9 DE JULIO 1472
4        19 DE MARZO 234
Name: direccion, dtype: object

In [ ]:
 bs_maestro_suc['direccion'].value_counts()

direccion
AV. SANTA FE                        4
AV. RIVADAVIA                       4
AV. CORRIENTES                      3
COLON                               3
AV. CABILDO                         2
                                   ..
BELGRANO 3182                       1
DARDO ROCHA N 2300                  1
BUENOS AIRES 902                    1
AV. ALTE. BROWN 407 ESQ. AV. ACA    1
AV. RIVADAVIA 16313                 1
Name: count, Length: 414, dtype: int64

In [ ]:
 bs_maestro_suc[bs_maestro_suc['direccion'].isna()]

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
234,235,2011-02-28,NaN,NaN,NaN,NaN,08:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,Cerrado,Cerrado,NaN,NaN
421,422,2016-01-13,BELGRANO CENTRAL,NaN,BELGRANO,CAPITAL FEDERAL,07:00-21:00,07:00-21:00,07:00-21:00,08:00-21:00,07:00-21:00,Cerrado,10:00-20:00,NaN,NaN

Son dos las sucursales que no continen dirección

Detectamos que hay varias direcciones sin número, antes de avanzar vamos a estandarizar en minúsculas todo el campo "dirección".

In [ ]:
 bs_maestro_suc['direccion'] =  bs_maestro_suc['direccion'].str.lower()
 bs_maestro_suc['direccion'].head()

0       av. libertad 569
1          rivadavia 197
2           av. santa fe
3    av. 9 de julio 1472
4        19 de marzo 234
Name: direccion, dtype: object

In [ ]:
 bs_maestro_suc['direccion'].value_counts()

direccion
av. santa fe                       4
av. rivadavia                      4
colon                              3
av. corrientes                     3
av. san martin                     2
                                  ..
av. f. fernandez de la cruz 809    1
belgrano 3182                      1
dardo rocha n 2300                 1
buenos aires 902                   1
av. rivadavia 16313                1
Name: count, Length: 413, dtype: int64

En las de mayor repetición no parece haber cambios con la conversión a minúsculas

In [ ]:
bs_maestro_suc[bs_maestro_suc['direccion'].isna()]

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
119,120,2006-10-10,CASILDA,NaN,CASILDA,SANTA FE,07:00-21:00,08:00-21:00,08:00-21:00,07:00-22:00,07:00-22:00,10:00-20:00,Cerrado,NaN,NaN
234,235,2011-02-28,NaN,NaN,NaN,NaN,08:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,Cerrado,Cerrado,NaN,NaN
421,422,2016-01-13,BELGRANO CENTRAL,NaN,BELGRANO,CAPITAL FEDERAL,07:00-21:00,07:00-21:00,07:00-21:00,08:00-21:00,07:00-21:00,Cerrado,10:00-20:00,NaN,NaN

La dirección de la sucursal 120 que era un número ahora es NaN, por la conversión a texto. Debido al análisis y tratamiento que vamos a llevar adelante, no recuperaremos el número por ser irrelevante para trabajo, cómo tampoco profundizaremos en los datos faltantes de la dirección.

###Campo Localidad

In [ ]:
bs_maestro_suc['localidad'].head()

0    S S JUJUY
1      CORDOBA
2      PALERMO
3        LANUS
4       ZARATE
Name: localidad, dtype: object

In [ ]:
bs_maestro_suc['localidad'].value_counts()

localidad
CORDOBA        22
MICROCENTRO    16
BELGRANO       14
ROSARIO        13
SANTA FE       10
               ..
FLORIDA         1
USHUAIA         1
ENTRE RIOS      1
SAN NICOLAS     1
MAR DE AJO      1
Name: count, Length: 177, dtype: int64

In [ ]:
localidades = bs_maestro_suc['localidad'].fillna('').to_list()
localidades = sorted(localidades, key=len, reverse=True)
localidades[:10]

['Rosario -Pcia. de Santa F',
 'VILLA BELGRANO - CORDOBA',
 'CONCEPCION DEL URUGUAY',
 'SAN ANTONIO DE ARECO',
 'MALVINAS ARGENTINAS',
 'COMODORO RIVADAVIA',
 'COMODORO RIVADAVIA',
 'COMODORO RIVADAVIA',
 'CAPILLA DEL SEÑOR',
 'CAPILLA DEL SEÑOR']

In [ ]:
localidades_text = [x for x in localidades if not isinstance(x, str)]
localidades_text

[]

Las localidades son textos, salvo el nulo del idSucursal 235.

In [ ]:
localidades_null = bs_maestro_suc['localidad'][bs_maestro_suc['localidad'].isnull()]
localidades_null

234    NaN
Name: localidad, dtype: object

Detectamos que es posible que haya ciudades con la provincia, en ambos casos están separados por un "-", analizaremos cuantas son las que tienen el separador.

In [ ]:
caracteres_defiltro = "[-]"
localidades_caract = bs_maestro_suc[bs_maestro_suc['localidad'].str.contains(caracteres_defiltro, regex=True, na=False)]
localidades_caract

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
90,91,2004-12-01,ARROYO SECO,mitre 277,Rosario -Pcia. de Santa F,SANTA FE,07:00-21:00,07:00-22:00,08:00-21:00,07:00-21:00,07:00-21:00,08:00-21:00,10:00-14:00,NaN,NaN
419,420,2016-01-04,VILLA CARLOS PAZ (CÓRDOBA),alberdi 37,VILLA BELGRANO - CORDOBA,CORDOBA,07:00-22:00,08:00-21:00,07:00-21:00,08:00-21:00,07:00-22:00,Cerrado,09:00-21:00,NaN,NaN

Ambas sucursales ya tienen cargadas las provincias, por lo que avanzaremos eliminando el texto posterior al "-".

Iteramos sobre la columna 'localidad', verificando si el valor es un string, y de tener "-" dividimos y nos quedamos con la primer parte de la cadena.

In [ ]:
for idx in range(len(bs_maestro_suc)):
    if isinstance(bs_maestro_suc.loc[idx, 'localidad'], str):
        bs_maestro_suc.loc[idx, 'localidad'] = bs_maestro_suc.loc[idx, 'localidad'].split('-')[0]

Test de que fueron actualizadas correctamente.

In [ ]:
bs_maestro_suc[(bs_maestro_suc['idSucursal']==91) | (bs_maestro_suc['idSucursal']==420)]

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
90,91,2004-12-01,ARROYO SECO,mitre 277,Rosario,SANTA FE,07:00-21:00,07:00-22:00,08:00-21:00,07:00-21:00,07:00-21:00,08:00-21:00,10:00-14:00,NaN,NaN
419,420,2016-01-04,VILLA CARLOS PAZ (CÓRDOBA),alberdi 37,VILLA BELGRANO,CORDOBA,07:00-22:00,08:00-21:00,07:00-21:00,08:00-21:00,07:00-22:00,Cerrado,09:00-21:00,NaN,NaN

Por último vamos a estandarizar el nombre de las localidades pasandolas a mayúsculas.

In [ ]:
bs_maestro_suc[bs_maestro_suc['localidad'].isna()]

,idSucursal,fechaAlta,nombre,direccion,localidad,provincia,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo,fechaBaja,estado
234,235,2011-02-28,NaN,NaN,NaN,NaN,08:00-21:00,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,Cerrado,Cerrado,NaN,NaN

Solo la localidad de la idSucursal 235 es NaN

In [ ]:
bs_maestro_suc['localidad'] = bs_maestro_suc['localidad'].str.upper()

###Campo Provincia

In [ ]:
bs_maestro_suc['provincia'].head()

0              JUJUY
1            CORDOBA
2    CAPITAL FEDERAL
3       BUENOS AIRES
4       BUENOS AIRES
Name: provincia, dtype: object

In [ ]:
bs_maestro_suc['provincia'].value_counts().sort_values()

provincia
CATAMARCA                1
LA RIOJA                 1
LA PAMPA                 2
JUJUY                    2
TIERRA DEL FUEGO         2
SANTA CRUZ               3
CORRIENTES               4
SANTIAGO DEL ESTERO      4
MISIONES                 4
SAN LUIS                 4
NEUQUEN                  4
SAN JUAN                 5
RIO NEGRO                5
CHUBUT                   5
SALTA                    5
CHACO                    5
TUCUMAN                  8
ENTRE RIOS              11
MENDOZA                 15
CORDOBA                 31
SANTA FE                34
CAPITAL FEDERAL        110
BUENOS AIRES           167
Name: count, dtype: int64

###Campo Horarios

In [ ]:
bs_maestro_suc['horarioLunes'].value_counts()

horarioLunes
07:00-21:00    155
07:00-22:00    150
08:00-21:00    128
Name: count, dtype: int64

In [ ]:
bs_maestro_suc['horarioMartes'].value_counts()

horarioMartes
07:00-22:00    153
07:00-21:00    146
08:00-21:00    134
Name: count, dtype: int64

In [ ]:
bs_maestro_suc['horarioMiercoles'].value_counts()

horarioMiercoles
07:00-22:00    152
08:00-21:00    144
07:00-21:00    137
Name: count, dtype: int64

In [ ]:
bs_maestro_suc['horarioJueves'].value_counts()

horarioJueves
07:00-21:00    149
08:00-21:00    145
07:00-22:00    139
Name: count, dtype: int64

In [ ]:
bs_maestro_suc['horarioViernes'].value_counts()

horarioViernes
07:00-22:00    150
08:00-21:00    146
07:00-21:00    137
Name: count, dtype: int64

In [ ]:
bs_maestro_suc['horarioSabado'].value_counts()

horarioSabado
10:00-14:00    103
09:00-21:00     86
08:00-21:00     85
Cerrado         84
10:00-20:00     75
Name: count, dtype: int64

In [ ]:
bs_maestro_suc['horarioDomingo'].value_counts()

horarioDomingo
08:00-21:00    93
10:00-20:00    88
Cerrado        86
10:00-14:00    83
09:00-21:00    83
Name: count, dtype: int64

Los horarios estan tipificados, deberémos aplicar las formas normales para optimizar la base.

In [ ]:
bs_maestro_suc['fechaBaja'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
bs_maestro_suc['estado'].value_counts()

Series([], Name: count, dtype: int64)

##Formas Normales

De la aplicación de las formas normales surge generar 6 tablas nuevas, reduciendo la redundancia y optimizando para un modelo OLTP

###Subtabla 1

In [ ]:
bs_maestro_suc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433 entries, 0 to 432
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   idSucursal        433 non-null    int64
 1   fechaAlta         433 non-null    datetime64[ns]
 2   nombre            432 non-null    object
 3   direccion         430 non-null    object
 4   localidad         432 non-null    object
 5   provincia         432 non-null    object
 6   horarioLunes      433 non-null    object
 7   horarioMartes     433 non-null    object
 8   horarioMiercoles  433 non-null    object
 9   horarioJueves     433 non-null    object
 10  horarioViernes    433 non-null    object
 11  horarioSabado     433 non-null    object
 12  horarioDomingo    433 non-null    object
 13  fechaBaja         0 non-null      float64
 14  estado            0 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(11)
memory usage: 50.9+ KB

In [ ]:
bs_maestro_suc_1 = bs_maestro_suc[['idSucursal','nombre','fechaAlta','fechaBaja','estado']]
bs_maestro_suc_1.head()

   idSucursal                    nombre  fechaAlta  fechaBaja  estado
0           1  LIBERTOR GRAL SAN MARTIN 2000-01-12        NaN     NaN
1           2              CRUZ DEL EJE 2000-01-14        NaN     NaN
2           3           AV CORONEL DIAZ 2000-03-01        NaN     NaN
3           4                LANUS ESTE 2000-03-04        NaN     NaN
4           5                    ZARATE 2000-04-09        NaN     NaN

###Subtabla 2

In [ ]:
bs_maestro_suc_2 = bs_maestro_suc[['idSucursal','direccion','localidad','provincia']]
bs_maestro_suc_2.head()

   idSucursal            direccion  localidad        provincia
0           1     av. libertad 569  S S JUJUY            JUJUY
1           2        rivadavia 197    CORDOBA          CORDOBA
2           3         av. santa fe    PALERMO  CAPITAL FEDERAL
3           4  av. 9 de julio 1472      LANUS     BUENOS AIRES
4           5      19 de marzo 234     ZARATE     BUENOS AIRES

In [ ]:
bs_maestro_suc_2 = bs_maestro_suc_2.assign(id_provincia=pd.factorize(bs_maestro_suc_2['provincia'], sort=True)[0])

In [ ]:
bs_maestro_suc_2.head()

   idSucursal            direccion  localidad        provincia  id_provincia
0           1     av. libertad 569  S S JUJUY            JUJUY             8
1           2        rivadavia 197    CORDOBA          CORDOBA             5
2           3         av. santa fe    PALERMO  CAPITAL FEDERAL             1
3           4  av. 9 de julio 1472      LANUS     BUENOS AIRES             0
4           5      19 de marzo 234     ZARATE     BUENOS AIRES             0

Para que las provincias arranquen en 1, sumamos 1 al id.

In [ ]:
bs_maestro_suc_2['id_provincia'] = bs_maestro_suc_2['id_provincia']+1

###Subtabla 3

Creamos la tabla 3, que contiene id provincia y el nombre de la provincia.

In [ ]:
bs_maestro_suc_3 = bs_maestro_suc_2[['id_provincia','provincia']].drop_duplicates()
bs_maestro_suc_3 = bs_maestro_suc_3.sort_values(by='id_provincia')
bs_maestro_suc_3

     id_provincia            provincia
234             0                  NaN
3               1         BUENOS AIRES
2               2      CAPITAL FEDERAL
299             3            CATAMARCA
29              4                CHACO
7               5               CHUBUT
1               6              CORDOBA
125             7           CORRIENTES
15              8           ENTRE RIOS
0               9                JUJUY
138            10             LA PAMPA
65             11             LA RIOJA
10             12              MENDOZA
26             13             MISIONES
238            14              NEUQUEN
23             15            RIO NEGRO
30             16                SALTA
69             17             SAN JUAN
79             18             SAN LUIS
52             19           SANTA CRUZ
40             20             SANTA FE
43             21  SANTIAGO DEL ESTERO
178            22     TIERRA DEL FUEGO
6              23              TUCUMAN

Dejamos entonces con id solo la provincia.

In [ ]:
bs_maestro_suc_2 = bs_maestro_suc_2.drop(columns=['provincia'])
bs_maestro_suc_2.head()

   idSucursal            direccion  localidad  id_provincia
0           1     av. libertad 569  S S JUJUY             9
1           2        rivadavia 197    CORDOBA             6
2           3         av. santa fe    PALERMO             2
3           4  av. 9 de julio 1472      LANUS             1
4           5      19 de marzo 234     ZARATE             1

###Subtabla 5

La 4ta tabla es la relación id sucursal con id del día e id del horario necesitamos despivotear la tabla.

In [ ]:
bs_maestro_suc.columns

Index(['idSucursal', 'fechaAlta', 'nombre', 'direccion', 'localidad',
       'provincia', 'horarioLunes', 'horarioMartes', 'horarioMiercoles',
       'horarioJueves', 'horarioViernes', 'horarioSabado', 'horarioDomingo',
       'fechaBaja', 'estado'],
      dtype='object')

In [ ]:
bs_maestro_suc_4 = bs_maestro_suc[['idSucursal','horarioLunes', 'horarioMartes', 'horarioMiercoles',
       'horarioJueves', 'horarioViernes', 'horarioSabado', 'horarioDomingo']]
bs_maestro_suc_4

,idSucursal,horarioLunes,horarioMartes,horarioMiercoles,horarioJueves,horarioViernes,horarioSabado,horarioDomingo
0,1,08:00-21:00,07:00-21:00,07:00-21:00,07:00-21:00,07:00-21:00,10:00-20:00,10:00-20:00
1,2,08:00-21:00,08:00-21:00,07:00-22:00,07:00-22:00,07:00-21:00,08:00-21:00,08:00-21:00
2,3,07:00-22:00,07:00-21:00,07:00-22:00,08:00-21:00,07:00-22:00,10:00-20:00,10:00-14:00
3,4,07:00-22:00,07:00-22:00,08:00-21:00,07:00-22:00,07:00-22:00,08:00-21:00,08:00-21:00
4,5,08:00-21:00,07:00-21:00,08:00-21:00,08:00-21:00,07:00-22:00,10:00-20:00,09:00-21:00
...,...,...,...,...,...,...,...,...
428,429,07:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,07:00-22:00,Cerrado,08:00-21:00
429,430,07:00-22:00,07:00-22:00,08:00-21:00,07:00-21:00,08:00-21:00,10:00-14:00,09:00-21:00
430,431,08:00-21:00,07:00-22:00,07:00-21:00,07:00-21:00,07:00-21:00,10:00-20:00,Cerrado
431,432,07:00-22:00,08:00-21:00,07:00-21:00,08:00-21:00,08:00-21:00,08:00-21:00,08:00-21:00
432,433,07:00-21:00,07:00-22:00,07:00-22:00,07:00-21:00,07:00-22:00,09:00-21:00,10:00-20:00

In [ ]:
bs_maestro_suc_4_unpivoted = bs_maestro_suc_4.melt(id_vars=['idSucursal'],
                                                 value_vars=['horarioLunes', 'horarioMartes', 'horarioMiercoles', 'horarioJueves', 'horarioViernes', 'horarioSabado', 'horarioDomingo'],
                                                 var_name='dia',
                                                 value_name='horario')
dia_mapping = {
    'horarioLunes': 'Lunes',
    'horarioMartes': 'Martes',
    'horarioMiercoles': 'Miercoles',
    'horarioJueves': 'Jueves',
    'horarioViernes': 'Viernes',
    'horarioSabado': 'Sabado',
    'horarioDomingo': 'Domingo'
}

bs_maestro_suc_4_unpivoted['dia'] = bs_maestro_suc_4_unpivoted['dia'].map(dia_mapping)

bs_maestro_suc_4_unpivoted.head()

   idSucursal    dia      horario
0           1  Lunes  08:00-21:00
1           2  Lunes  08:00-21:00
2           3  Lunes  07:00-22:00
3           4  Lunes  07:00-22:00
4           5  Lunes  08:00-21:00

Creamos un id para cada día

In [ ]:
orden_dias = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']
mapeo_dias = {dia: idx + 1 for idx, dia in enumerate(orden_dias)}
bs_maestro_suc_4_unpivoted['id_dia'] = bs_maestro_suc_4_unpivoted['dia'].map(mapeo_dias)
bs_maestro_suc_4_unpivoted['id_dia'] = bs_maestro_suc_4_unpivoted['id_dia'].astype(int)
bs_maestro_suc_4_unpivoted.head()

   idSucursal    dia      horario  id_dia
0           1  Lunes  08:00-21:00       1
1           2  Lunes  08:00-21:00       1
2           3  Lunes  07:00-22:00       1
3           4  Lunes  07:00-22:00       1
4           5  Lunes  08:00-21:00       1

Creamos un id para horario

In [ ]:
bs_maestro_suc_4_unpivoted = bs_maestro_suc_4_unpivoted.assign(id_horario=pd.factorize(bs_maestro_suc_4_unpivoted['horario'], sort=True)[0])
bs_maestro_suc_4_unpivoted.head()

   idSucursal    dia      horario  id_dia  id_horario
0           1  Lunes  08:00-21:00       1           2
1           2  Lunes  08:00-21:00       1           2
2           3  Lunes  07:00-22:00       1           1
3           4  Lunes  07:00-22:00       1           1
4           5  Lunes  08:00-21:00       1           2

In [ ]:
bs_maestro_suc_5 = bs_maestro_suc_4_unpivoted[['id_dia','dia']].drop_duplicates()
bs_maestro_suc_5

      id_dia        dia
0          1      Lunes
433        2     Martes
866        3  Miercoles
1299       4     Jueves
1732       5    Viernes
2165       6     Sabado
2598       7    Domingo

###Subtabla 6

In [ ]:
bs_maestro_suc_6 = bs_maestro_suc_4_unpivoted[['id_horario','horario']].drop_duplicates()
bs_maestro_suc_6 = bs_maestro_suc_6.sort_values(by='id_horario')
bs_maestro_suc_6

      id_horario      horario
6              0  07:00-21:00
2              1  07:00-22:00
0              2  08:00-21:00
2176           3  09:00-21:00
2174           4  10:00-14:00
2165           5  10:00-20:00
2170           6      Cerrado

Para aplicar la 1FN separaremos los valores de horario, en horario de apertura y de cierre.

In [ ]:
bs_maestro_suc_6[['hs_apertura', 'hs_cierre']] = bs_maestro_suc_6['horario'].str.split('-', expand=True)
bs_maestro_suc_6

      id_horario      horario hs_apertura hs_cierre
6              0  07:00-21:00       07:00     21:00
2              1  07:00-22:00       07:00     22:00
0              2  08:00-21:00       08:00     21:00
2176           3  09:00-21:00       09:00     21:00
2174           4  10:00-14:00       10:00     14:00
2165           5  10:00-20:00       10:00     20:00
2170           6      Cerrado     Cerrado      None

In [ ]:
bs_maestro_suc_6['estado'] = bs_maestro_suc_6['horario'].apply(lambda x: 'Abierto' if 'Cerrado' not in x else 'Cerrado')
bs_maestro_suc_6

      id_horario      horario hs_apertura hs_cierre   estado
6              0  07:00-21:00       07:00     21:00  Abierto
2              1  07:00-22:00       07:00     22:00  Abierto
0              2  08:00-21:00       08:00     21:00  Abierto
2176           3  09:00-21:00       09:00     21:00  Abierto
2174           4  10:00-14:00       10:00     14:00  Abierto
2165           5  10:00-20:00       10:00     20:00  Abierto
2170           6      Cerrado     Cerrado      None  Cerrado

In [ ]:
bs_maestro_suc_6.loc[bs_maestro_suc_6['estado'] == 'Cerrado', ['hs_apertura', 'hs_cierre']] = None
bs_maestro_suc_6

      id_horario      horario hs_apertura hs_cierre   estado
6              0  07:00-21:00       07:00     21:00  Abierto
2              1  07:00-22:00       07:00     22:00  Abierto
0              2  08:00-21:00       08:00     21:00  Abierto
2176           3  09:00-21:00       09:00     21:00  Abierto
2174           4  10:00-14:00       10:00     14:00  Abierto
2165           5  10:00-20:00       10:00     20:00  Abierto
2170           6      Cerrado        None      None  Cerrado

In [ ]:
bs_maestro_suc_6 = bs_maestro_suc_6.drop(columns='horario')
bs_maestro_suc_6 = bs_maestro_suc_6.reset_index(drop=True)
bs_maestro_suc_6

   id_horario hs_apertura hs_cierre   estado
0           0       07:00     21:00  Abierto
1           1       07:00     22:00  Abierto
2           2       08:00     21:00  Abierto
3           3       09:00     21:00  Abierto
4           4       10:00     14:00  Abierto
5           5       10:00     20:00  Abierto
6           6        None      None  Cerrado

###Subtabla 4

In [ ]:
bs_maestro_suc_4_unpivoted = bs_maestro_suc_4_unpivoted.drop(columns= ['dia','horario'])
bs_maestro_suc_4_unpivoted

      idSucursal  id_dia  id_horario
0              1       1           2
1              2       1           2
2              3       1           1
3              4       1           1
4              5       1           2
...          ...     ...         ...
3026         429       7           2
3027         430       7           3
3028         431       7           6
3029         432       7           2
3030         433       7           5

[3031 rows x 3 columns]

##Carga a CSV

In [ ]:
bs_maestro_suc_6.to_csv('bs_maestro_suc_6.csv', index=False)
bs_maestro_suc_4_unpivoted.to_csv('bs_maestro_suc_4_unpivoted.csv', index=False)
bs_maestro_suc_5.to_csv('bs_maestro_suc_5.csv', index=False)
bs_maestro_suc_3.to_csv('bs_maestro_suc_3.csv', index=False)
bs_maestro_suc_2.to_csv('bs_maestro_suc_2.csv', index=False)
bs_maestro_suc_1.to_csv('bs_maestro_suc_1.csv', index=False)

##Creación Base SQL - en servidor

In [ ]:
###SQL para bs_maestro_suc_1.csv:
CREATE TABLE bs_maestro_suc_1 (
  idSucursal INT,
  nombre VARCHAR(255),
  fechaAlta VARCHAR(255),
  fechaBaja FLOAT,
  estado FLOAT
);

###SQL para bs_maestro_suc_2.csv:
CREATE TABLE bs_maestro_suc_2 (
  idSucursal INT,
  direccion VARCHAR(255),
  localidad VARCHAR(255),
  id_provincia INT
);

###SQL para bs_maestro_suc_3.csv:
CREATE TABLE bs_maestro_suc_3 (
  id_provincia INT,
  provincia VARCHAR(255)
);

###SQL para bs_maestro_suc_4_unpivoted.csv:
CREATE TABLE bs_maestro_suc_4_unpivoted (
  idSucursal INT,
  id_dia INT,
  id_horario INT
);

###SQL para bs_maestro_suc_5.csv:
CREATE TABLE bs_maestro_suc_5 (
  id_dia INT,
  dia VARCHAR(255)
);

###SQL para bs_maestro_suc_6.csv:
CREATE TABLE bs_maestro_suc_6 (
  id_horario INT,
  hs_apertura VARCHAR(255),
  hs_cierre VARCHAR(255),
  estado VARCHAR(255)
);

##Carga SQL

In [ ]:
# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["bs_maestro_suc_1.csv", "bs_maestro_suc_2.csv", "bs_maestro_suc_3.csv", "bs_maestro_suc_4.csv", "bs_maestro_suc_5.csv","bs_maestro_suc_6.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")

#Tabla Maestro Productos:

 Nro |Column | Non-Null Count | Dtype |
----- |------- |-------------- |---- |
 0 |idProducto | 14834 non-null  | int64 |
 1 |fechaAlta | 14834 non-null   |datetime64[ns] |
 2 |descripcion |  14834 non-null  | object |
 3 |precioUnitario  | 14834 non-null   |float64 |
 4 |precio  | 11003 non-null   |object |
 5 |categoria | 14834 non-null   |object |
 6 |subCategoria | 14834 non-null   |object |
 7 |fechaBaja | 0 non-null |float64 |
 8 |estado | 0 non-null |float64

##Importar tabla

In [ ]:
bs_maestro_prod = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='Maestro PRODUCTOS')
bs_maestro_prod.shape

(14834, 9)

In [ ]:
bs_maestro_prod.head()

,idProducto,fechaAlta,descripcion,precioUnitario,precio,categoria,subCategoria,fechaBaja,estado
0,1,2000-01-02,Alimento A Base De Miel LAS PRADERAS Pot 250 Grm,22.49,Precio por 1 Kilo : $89.96,Alimentos Secos,Mermeladas Y Dulces,NaN,NaN
1,2,2000-01-02,Galletas Dulces GRANDIET Miel Cja 150 Grm,64.19,Precio por 1 Kilo : $427.93,Alimentos Secos,Galletitas,NaN,NaN
2,3,2000-01-02,Aplique Astra C/Manito Blanco . . .,288.80,NaN,Hogar,Iluminacion,NaN,NaN
3,4,2000-01-02,Tapa De Emp C / Sem 330 Grs Delicias Doradas,24.75,Precio por 1 Kilo escurrido: $75.00,Alimentos Frescos,Pastas,NaN,NaN
4,5,2000-01-02,Fideos Guiseros Sem. Mostachol superDip Paq 50...,10.99,Precio por 1 Kilo : $21.98,Alimentos Secos,Pastas,NaN,NaN

In [ ]:
bs_maestro_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14834 entries, 0 to 14833
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idProducto      14834 non-null  int64
 1   fechaAlta       14834 non-null  datetime64[ns]
 2   descripcion     14834 non-null  object
 3   precioUnitario  14834 non-null  float64
 4   precio          11003 non-null  object
 5   categoria       14834 non-null  object
 6   subCategoria    14834 non-null  object
 7   fechaBaja       0 non-null      float64
 8   estado          0 non-null      float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 1.0+ MB

##Control tabla

###Campo idProducto

In [ ]:
bs_maestro_prod['idProducto'].value_counts()

idProducto
1        1
9881     1
9883     1
9884     1
9885     1
        ..
4949     1
4950     1
4951     1
4952     1
14834    1
Name: count, Length: 14834, dtype: int64

###Campo fechaAlta

In [ ]:
años = bs_maestro_prod['fechaAlta'].dt.year
años.value_counts()

fechaAlta
2004    2454
2003    1943
2005    1894
2006    1889
2007    1827
2002    1378
2008    1243
2001     815
2009     777
2000     614
Name: count, dtype: int64

Es razonable el año de alta de cada producto.

###Campo descripcion

In [ ]:
bs_maestro_prod['descripcion'].sort_values(key=lambda x: x.str.len(), ascending = False)

8894     Medallones De Pollo GRANJA DEL SOL Listtos Fwp...
7643     Cereal NESTLE Fitness Copos De Trigo Arroz Inf...
5225     Saborizador ALICANTE  De Ensal Vinagreta Con C...
6120     Rollo Cocina SWEETY Doble Hoja Decorad Paq 3 U...
12941    Agua Mineral Sin Gas Villa Del Sur Levite Nja ...
                               ...
6178                                                Kaki -
12454                                               Embudo
12149                                                Globo
6841                                                 Juego
12161                                                  Mop
Name: descripcion, Length: 14834, dtype: object

La descripción no tiene nulos, tiene un detalle del producto, nos puede ayudar a profundizar en alguna carácteristica del mismo.

###Campo precioUnitario

In [ ]:
bs_maestro_prod['precioUnitario'].value_counts()

precioUnitario
39.59     99
32.09     87
199.00    84
42.79     82
21.39     82
          ..
82.29      1
799.90     1
122.40     1
738.20     1
14.10      1
Name: count, Length: 2705, dtype: int64

In [ ]:
bs_maestro_prod[bs_maestro_prod['precioUnitario']<0]

Empty DataFrame
Columns: [idProducto, fechaAlta, descripcion, precioUnitario, precio, categoria, subCategoria, fechaBaja, estado]
Index: []

No hay precios errores de precio negativo

In [ ]:
bs_maestro_prod[bs_maestro_prod['precioUnitario'].isnull()]

Empty DataFrame
Columns: [idProducto, fechaAlta, descripcion, precioUnitario, precio, categoria, subCategoria, fechaBaja, estado]
Index: []

No hay precios unitarios nulos

###Campo precio

In [ ]:
bs_maestro_prod['precio'].head()

0             Precio por 1 Kilo : $89.96
1            Precio por 1 Kilo : $427.93
2                                    NaN
3    Precio por 1 Kilo escurrido: $75.00
4             Precio por 1 Kilo : $21.98
Name: precio, dtype: object

Tenemos un texto que tiene nulos, unidad, unidad de medida y precio. Debemos serparalos

In [ ]:
bs_maestro_prod[['cant_medida', 'unidad_medida', 'precio_uni_medida']] = bs_maestro_prod['precio'].str.extract(r'(\d+)\s+([a-zA-Z\s]+):\s*\$(\d+\.\d{2})')
print(bs_maestro_prod[['cant_medida', 'unidad_medida', 'precio_uni_medida']])

      cant_medida   unidad_medida precio_uni_medida
0               1           Kilo              89.96
1               1           Kilo             427.93
2             NaN             NaN               NaN
3               1  Kilo escurrido             75.00
4               1           Kilo              21.98
...           ...             ...               ...
14829           1          Litro              36.38
14830           1          Litro             162.25
14831         NaN             NaN               NaN
14832         100         Gramos              74.90
14833         100         Gramos              23.84

[14834 rows x 3 columns]

In [ ]:
bs_maestro_prod['unidad_medida'].value_counts()

unidad_medida
Litro                  3948
Kilo                   3071
Unidad                 1579
Gramos                  623
Kilogramo               572
Kilo escurrido          477
Kilogramo escurrido     240
Mililitros              129
Metro                    47
Cuadrado                 34
Saquito                  21
Medida                   13
Plancha                  12
Gramos escurridos        10
Sobre                     8
Unidad escurrido          1
Litro escurrido           1
Name: count, dtype: int64

Detectamos que Kilogramo y Kilo estan considerados separados, tanto en la unidad como en escurrido, dejaremos Kilogramo como correcto.

In [ ]:
bs_maestro_prod['unidad_medida'] = bs_maestro_prod['unidad_medida'].apply(lambda x: "Kilogramo" if pd.notna(x) and x.strip().lower() == "kilo" else x)

In [ ]:
bs_maestro_prod['unidad_medida'].value_counts()

unidad_medida
Litro                  3948
Kilogramo              3071
Unidad                 1579
Gramos                  623
Kilogramo               572
Kilo escurrido          477
Kilogramo escurrido     240
Mililitros              129
Metro                    47
Cuadrado                 34
Saquito                  21
Medida                   13
Plancha                  12
Gramos escurridos        10
Sobre                     8
Unidad escurrido          1
Litro escurrido           1
Name: count, dtype: int64

Falta reemplazar kilo escurrido por kilogramo escurrido, para unificar, ademas de eliminar posibles espacios y por último estandarizar en letra minúscula.

In [ ]:
bs_maestro_prod['unidad_medida'] = bs_maestro_prod['unidad_medida'].apply(lambda x: "kilogramo escurrido" if pd.notna(x) and x.strip().lower() == "kilo escurrido" else x)

In [ ]:
bs_maestro_prod['unidad_medida'] = bs_maestro_prod['unidad_medida'].str.strip().str.lower()

In [ ]:
bs_maestro_prod['unidad_medida'].value_counts().sort_index()

unidad_medida
cuadrado                 34
gramos                  623
gramos escurridos        10
kilogramo              3643
kilogramo escurrido     717
litro                  3948
litro escurrido           1
medida                   13
metro                    47
mililitros              129
plancha                  12
saquito                  21
sobre                     8
unidad                 1579
unidad escurrido          1
Name: count, dtype: int64

In [ ]:
bs_maestro_prod['cant_medida'].value_counts()

cant_medida
1      10024
100      762
Name: count, dtype: int64

Hay medidas que son unitarias otras en 100. revisaremos si hay equivalencias.

In [ ]:
bs_maestro_prod['cant_medida'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 14834 entries, 0 to 14833
Series name: cant_medida
Non-Null Count  Dtype
--------------  -----
10786 non-null  object
dtypes: object(1)
memory usage: 116.0+ KB

In [ ]:
un100_medida = bs_maestro_prod[bs_maestro_prod['cant_medida'] == "100"]
value_counts = un100_medida['unidad_medida'].value_counts()

print(value_counts)

unidad_medida
gramos               623
mililitros           129
gramos escurridos     10
Name: count, dtype: int64

Los 100 gramos, mililitros y gramos escurridos no hacen equivalencia de otro valor que ya esté calculado.

###Campo categoria

In [ ]:
bs_maestro_prod['categoria'].value_counts()

categoria
Alimentos Secos      3476
Otros                2215
Perfumería           2108
Bebidas              2052
Alimentos Frescos    1722
Limpieza             1377
Hogar                 998
Textil                454
Aire Libre            308
Electrodomesticos     124
Name: count, dtype: int64

En la categoría no hay nulos, ni valores diferentes a las 10 categorías.

###Campo subCategoria

In [ ]:
bs_maestro_prod['subCategoria'].value_counts()

subCategoria
Bebidas Con Alcohol    1451
Cuidado Del Cabello     731
Bazar                   642
Bebidas Sin Alcohol     560
Automotor               434
                       ...
Electro Hogar             2
Heladeras Y Freezer       2
Protectores Solares       2
Alcohol De Quemar         1
Ayudantes De Cocina       1
Name: count, Length: 124, dtype: int64

para eliminar posibles errores procedemos a pasar todo a minúsculas.

In [ ]:
bs_maestro_prod['subCategoria'] = bs_maestro_prod['subCategoria'].str.lower()
bs_maestro_prod['subCategoria'].value_counts()

subCategoria
bebidas con alcohol    1451
cuidado del cabello     731
bazar                   642
bebidas sin alcohol     560
automotor               434
                       ...
electro hogar             2
heladeras y freezer       2
protectores solares       2
alcohol de quemar         1
ayudantes de cocina       1
Name: count, Length: 124, dtype: int64

In [ ]:
caracteres_defiltro = "[-]"
localidades_caract = bs_maestro_prod[bs_maestro_prod['subCategoria'].str.contains(caracteres_defiltro, regex=True, na=False)]
localidades_caract['subCategoria'].value_counts()

subCategoria
panadería - elaboración propia             118
bizcochuelos - budines - especialidades     89
oferta - vinos en caja                      41
Name: count, dtype: int64

Consideramos que tanto los elementos de panadería de elaboración propia, como los bizcochuelos, no es un error considerarlos como una categoría aparte de productos. Si considerar los vinos en caja en oferta como una categoría diferente a bebidas con alcohol o sin alcohol. Esta identificación como bebida en oferta debería hacerse en otro nivel de clasificación del producto. Proponemos crear una nueva columna con la etiqueta de oferta del vino en caja, pero en la subCategoría clasificarlos como bebidas con alcohol.

In [ ]:
bs_maestro_prod['tiene_oferta'] = bs_maestro_prod['subCategoria'] == "oferta - vinos en caja"

In [ ]:
bs_maestro_prod['subCategoria'] = bs_maestro_prod['subCategoria'].str.replace("oferta - vinos en caja", "bebidas con alcohol", case=False)

In [ ]:
test_bebidas = bs_maestro_prod[bs_maestro_prod['categoria']=="Bebidas"]
test_bebidas['subCategoria'].value_counts()

subCategoria
bebidas con alcohol    1492
bebidas sin alcohol     560
Name: count, dtype: int64

Las bebidas se sub-categorizaron todas con alcohol o sin alcohol.

In [ ]:
category_count = bs_maestro_prod.groupby('subCategoria')['categoria'].nunique()
multiple_categories = category_count[category_count > 1]
multiple_categories

subCategoria
pastas    2
Name: categoria, dtype: int64

La categoría pastas es la única que se repite en dos categorías distintas, para mejorar la organización de las tablas, vamos a cambiar si el producto es "pasta fresca" si pertenece a alimentos frescos, y a "pasta seca" si pertenece a alimentos secos.

In [ ]:
bs_maestro_prod.loc[
    (bs_maestro_prod['categoria'] == 'Alimentos Frescos') &
    (bs_maestro_prod['subCategoria'] == 'pastas'),
    'subCategoria'
] = 'pastas frescas'

bs_maestro_prod.loc[
    (bs_maestro_prod['categoria'] == 'Alimentos Secos') &
    (bs_maestro_prod['subCategoria'] == 'pastas'),
    'subCategoria'
] = 'pastas secas'

In [ ]:
bs_maestro_prod[bs_maestro_prod['subCategoria']=="pastas secas"]

,idProducto,fechaAlta,descripcion,precioUnitario,precio,categoria,subCategoria,fechaBaja,estado,cant_medida,unidad_medida,precio_uni_medida,tiene_oferta
4,5,2000-01-02,Fideos Guiseros Sem. Mostachol superDip Paq 50...,10.99,Precio por 1 Kilo : $21.98,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,21.98,False
12,13,2000-01-04,Fideos Largos Sem. MATARAZZO Spaghetti Morron ...,21.39,Precio por 1 Kilo : $42.78,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,42.78,False
144,145,2000-03-29,Fideos Largos Sem. MATARAZZO Spaghetti Paq 500...,17.99,Precio por 1 Kilo : $35.98,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,35.98,False
203,204,2000-05-07,Fideos Guiseros Sem/Huevo Tirabuzon GRIMALDI P...,22.99,Precio por 1 Kilo : $45.98,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,45.98,False
250,251,2000-06-02,Fideos Largos Sem. BARILLA Spaghetti Cja 500 Grm,90.95,Precio por 1 Kilo : $181.90,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,181.90,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14553,14554,2009-05-25,Fideos Guiseros Sem. FAVORITA Mostachol Rayado...,9.90,Precio por 1 Kilo : $19.80,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,19.80,False
14580,14581,2009-06-02,Fideos Huevo DON ITALO Fettuccine Nº 42 Cja 50...,61.85,Precio por 1 Kilo : $123.70,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,123.70,False
14586,14587,2009-06-03,Fideos Soperos Sem. KNORR Letras Paq 500 Grm,20.50,Precio por 1 Kilo : $41.00,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,41.00,False
14719,14720,2009-07-21,Fideos Largos Sem. TIBALDI Cinta Espinaca Est ...,56.70,Precio por 1 Kilo : $189.00,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,189.00,False
14827,14828,2009-09-27,Fideos Guiseros Huevo DON FELIPE Paq 500 Grm,28.75,Precio por 1 Kilo : $57.50,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,57.50,False

###Campo fechaBaja

###Campo estado

##Formas Normales

###Subtabla 1

In [ ]:
bs_maestro_prod.head()

,idProducto,fechaAlta,descripcion,precioUnitario,precio,categoria,subCategoria,fechaBaja,estado,cant_medida,unidad_medida,precio_uni_medida,tiene_oferta
0,1,2000-01-02,Alimento A Base De Miel LAS PRADERAS Pot 250 Grm,22.49,Precio por 1 Kilo : $89.96,Alimentos Secos,mermeladas y dulces,NaN,NaN,1,kilogramo,89.96,False
1,2,2000-01-02,Galletas Dulces GRANDIET Miel Cja 150 Grm,64.19,Precio por 1 Kilo : $427.93,Alimentos Secos,galletitas,NaN,NaN,1,kilogramo,427.93,False
2,3,2000-01-02,Aplique Astra C/Manito Blanco . . .,288.80,NaN,Hogar,iluminacion,NaN,NaN,NaN,NaN,NaN,False
3,4,2000-01-02,Tapa De Emp C / Sem 330 Grs Delicias Doradas,24.75,Precio por 1 Kilo escurrido: $75.00,Alimentos Frescos,pastas frescas,NaN,NaN,1,kilogramo escurrido,75.00,False
4,5,2000-01-02,Fideos Guiseros Sem. Mostachol superDip Paq 50...,10.99,Precio por 1 Kilo : $21.98,Alimentos Secos,pastas secas,NaN,NaN,1,kilogramo,21.98,False

In [ ]:
bs_maestro_prod.columns

Index(['idProducto', 'fechaAlta', 'descripcion', 'precioUnitario', 'precio',
       'categoria', 'subCategoria', 'fechaBaja', 'estado', 'cant_medida',
       'unidad_medida', 'precio_uni_medida', 'tiene_oferta'],
      dtype='object')

In [ ]:
bs_maestro_prod_1 = bs_maestro_prod[['idProducto', 'fechaAlta', 'descripcion', 'fechaBaja', 'estado', 'tiene_oferta']]
bs_maestro_prod_1

,idProducto,fechaAlta,descripcion,fechaBaja,estado,tiene_oferta
0,1,2000-01-02,Alimento A Base De Miel LAS PRADERAS Pot 250 Grm,NaN,NaN,False
1,2,2000-01-02,Galletas Dulces GRANDIET Miel Cja 150 Grm,NaN,NaN,False
2,3,2000-01-02,Aplique Astra C/Manito Blanco . . .,NaN,NaN,False
3,4,2000-01-02,Tapa De Emp C / Sem 330 Grs Delicias Doradas,NaN,NaN,False
4,5,2000-01-02,Fideos Guiseros Sem. Mostachol superDip Paq 50...,NaN,NaN,False
...,...,...,...,...,...,...
14829,14830,2009-09-28,Bebida Energizante GATORADE Manzana Bot 500 Cc,NaN,NaN,False
14830,14831,2009-09-30,Pinrura Latex Interior- Living Guarana-4 Lt,NaN,NaN,False
14831,14832,2009-10-01,Adhesivo X 50 Mililitros VOLIGOMA,NaN,NaN,False
14832,14833,2009-10-01,Crema Dental SENSODYNE Proesmalte Niño Pom 50 Grm,NaN,NaN,False
14833,14834,2009-10-01,Jugo TANG Manzana Sob 20 Grm,NaN,NaN,False

###Subtabla 3

In [ ]:
bs_maestro_prod_2 = bs_maestro_prod[['idProducto', 'precioUnitario', 'cant_medida', 'unidad_medida', 'precio_uni_medida']]
bs_maestro_prod_2

,idProducto,precioUnitario,cant_medida,unidad_medida,precio_uni_medida
0,1,22.49,1,kilogramo,89.96
1,2,64.19,1,kilogramo,427.93
2,3,288.80,NaN,NaN,NaN
3,4,24.75,1,kilogramo escurrido,75.00
4,5,10.99,1,kilogramo,21.98
...,...,...,...,...,...
14829,14830,18.19,1,litro,36.38
14830,14831,649.00,1,litro,162.25
14831,14832,14.10,NaN,NaN,NaN
14832,14833,37.45,100,gramos,74.90
14833,14834,4.29,100,gramos,23.84

In [ ]:
bs_maestro_prod_2 = bs_maestro_prod_2.assign(id_uni_medida=pd.factorize(bs_maestro_prod_2['unidad_medida'], sort=True)[0])
bs_maestro_prod_2.head()

,idProducto,precioUnitario,cant_medida,unidad_medida,precio_uni_medida,id_uni_medida
0,1,22.49,1,kilogramo,89.96,3
1,2,64.19,1,kilogramo,427.93,3
2,3,288.80,NaN,NaN,NaN,-1
3,4,24.75,1,kilogramo escurrido,75.00,4
4,5,10.99,1,kilogramo,21.98,3

In [ ]:
bs_maestro_prod_2['id_uni_medida']=bs_maestro_prod_2['id_uni_medida']+1

In [ ]:
bs_maestro_prod_3 = bs_maestro_prod_2[['id_uni_medida', 'unidad_medida']].drop_duplicates()
bs_maestro_prod_3 = bs_maestro_prod_3.sort_values(by='id_uni_medida')
bs_maestro_prod_3 = bs_maestro_prod_3.reset_index(drop=True)
bs_maestro_prod_3

    id_uni_medida        unidad_medida
0               0                  NaN
1               1             cuadrado
2               2               gramos
3               3    gramos escurridos
4               4            kilogramo
5               5  kilogramo escurrido
6               6                litro
7               7      litro escurrido
8               8               medida
9               9                metro
10             10           mililitros
11             11              plancha
12             12              saquito
13             13                sobre
14             14               unidad
15             15     unidad escurrido

In [ ]:
bs_maestro_prod_2 = bs_maestro_prod_2.drop(columns='unidad_medida')
bs_maestro_prod_2.head()

   idProducto  precioUnitario cant_medida precio_uni_medida  id_uni_medida
0           1           22.49           1             89.96              4
1           2           64.19           1            427.93              4
2           3          288.80         NaN               NaN              0
3           4           24.75           1             75.00              5
4           5           10.99           1             21.98              4

###Subtabla 2

In [ ]:
bs_maestro_prod_2 = bs_maestro_prod_2.reindex(['idProducto', 'precioUnitario', 'cant_medida', 'id_uni_medida', 'precio_uni_medida'], axis = 1)
bs_maestro_prod_2.head()

   idProducto  precioUnitario cant_medida  id_uni_medida precio_uni_medida
0           1           22.49           1              4             89.96
1           2           64.19           1              4            427.93
2           3          288.80         NaN              0               NaN
3           4           24.75           1              5             75.00
4           5           10.99           1              4             21.98

###Subtabla 5

In [ ]:
bs_maestro_prod_4 = bs_maestro_prod[['idProducto','subCategoria', 'categoria']]
bs_maestro_prod_4.head()

   idProducto         subCategoria          categoria
0           1  mermeladas y dulces    Alimentos Secos
1           2           galletitas    Alimentos Secos
2           3          iluminacion              Hogar
3           4       pastas frescas  Alimentos Frescos
4           5         pastas secas    Alimentos Secos

In [ ]:
bs_maestro_prod_4 = bs_maestro_prod_4.assign(idSubcategoria=pd.factorize(bs_maestro_prod_4['subCategoria'], sort=True)[0])
bs_maestro_prod_4['idSubcategoria'] = bs_maestro_prod_4['idSubcategoria']+1
bs_maestro_prod_4.head()

   idProducto         subCategoria          categoria  idSubcategoria
0           1  mermeladas y dulces    Alimentos Secos              85
1           2           galletitas    Alimentos Secos              55
2           3          iluminacion              Hogar              62
3           4       pastas frescas  Alimentos Frescos              93
4           5         pastas secas    Alimentos Secos              94

In [ ]:
bs_maestro_prod_5 = bs_maestro_prod_4[['idProducto','subCategoria', 'categoria', 'idSubcategoria']].drop_duplicates(subset='idSubcategoria', keep="last")
bs_maestro_prod_5.head()

       idProducto          subCategoria          categoria  idSubcategoria
3091         3092     alcohol de quemar           Limpieza               3
6643         6644   heladeras y freezer  Electrodomesticos              60
10057       10058  sombrillas / gazebos         Aire Libre             112
10262       10263          frutas secas    Alimentos Secos              53
10293       10294                 mamás         Perfumería              81

In [ ]:
bs_maestro_prod_5 = bs_maestro_prod_5.drop(columns='idProducto')
bs_maestro_prod_5 = bs_maestro_prod_5.reset_index(drop=True)
bs_maestro_prod_5 = bs_maestro_prod_5.reindex(['idSubcategoria','subCategoria','categoria'], axis = 1)
bs_maestro_prod_5.head()

   idSubcategoria          subCategoria          categoria
0               3     alcohol de quemar           Limpieza
1              60   heladeras y freezer  Electrodomesticos
2             112  sombrillas / gazebos         Aire Libre
3              53          frutas secas    Alimentos Secos
4              81                 mamás         Perfumería

###Subtabla 4

In [ ]:
bs_maestro_prod_4 = bs_maestro_prod_4.drop(columns=['subCategoria','categoria'])
bs_maestro_prod_4

       idProducto  idSubcategoria
0               1              85
1               2              55
2               3              62
3               4              93
4               5              94
...           ...             ...
14829       14830              18
14830       14831              50
14831       14832              76
14832       14833              61
14833       14834              18

[14834 rows x 2 columns]

##Carga CSV

In [ ]:
bs_maestro_prod_1.to_csv('bs_maestro_prod_1.csv', index=False)
bs_maestro_prod_2.to_csv('bs_maestro_prod_2.csv', index=False)
bs_maestro_prod_3.to_csv('bs_maestro_prod_3.csv', index=False)
bs_maestro_prod_4.to_csv('bs_maestro_prod_4.csv', index=False)
bs_maestro_prod_5.to_csv('bs_maestro_prod_5.csv', index=False)

##Creación Base SQL - en servidor

In [ ]:
###SQL para bs_maestro_prod_1.csv:
CREATE TABLE bs_maestro_prod_1 (
  idProducto INT,
  fechaAlta VARCHAR(255),
  descripcion VARCHAR(255),
  fechaBaja FLOAT,
  estado FLOAT,
  tiene_oferta VARCHAR(255)
);

###SQL para bs_maestro_prod_2.csv:
CREATE TABLE bs_maestro_prod_2 (
  idProducto INT,
  precioUnitario FLOAT,
  cant_medida FLOAT,
  id_uni_medida INT,
  precio_uni_medida FLOAT
);

###SQL para bs_maestro_prod_3.csv:
CREATE TABLE bs_maestro_prod_3 (
  id_uni_medida INT,
  unidad_medida VARCHAR(255)
);

###SQL para bs_maestro_prod_4.csv:
CREATE TABLE bs_maestro_prod_4 (
  idProducto INT,
  idSubcategoria INT
);

##Carga SQL

In [ ]:
# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["bs_maestro_prod_1.csv", "bs_maestro_prod_2.csv", "bs_maestro_prod_3.csv", "bs_maestro_prod_4.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")

#Tabla Inventario:

##Importar tabla

In [ ]:
bs_inventario = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='INVENTARIO')
bs_inventario.shape

(200000, 6)

In [ ]:
bs_inventario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idSucursal              200000 non-null  int64
 1   idProducto              200000 non-null  int64
 2   cantidadEnStock         200000 non-null  int64
 3   cantidadParaReposicion  200000 non-null  int64
 4   reposicionPedida        7994 non-null    float64
 5   cantidadPedida          6049 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 9.2 MB

##Control tabla

###Campo IdSucursal e IdProducto

La tabla muestra el inventario de cada sucursal de cada producto, por lo que la relación idSucursal idProducto debería ser unica.

In [ ]:
bs_inventario['id_inventario']= bs_inventario['idSucursal'].astype(str) +"_"+ bs_inventario['idProducto'].astype(str)
bs_inventario.head()

,idSucursal,idProducto,cantidadEnStock,cantidadParaReposicion,reposicionPedida,cantidadPedida,id_inventario
0,1,12168,819,500,NaN,NaN,1_12168
1,1,5320,2074,1500,NaN,NaN,1_5320
2,1,12938,1652,1400,NaN,NaN,1_12938
3,1,12093,2116,100,NaN,NaN,1_12093
4,1,8191,570,200,NaN,NaN,1_8191

In [ ]:
bs_inventario['id_inventario'].value_counts()

id_inventario
416_12161    4
21_7359      3
351_13804    3
39_12208     3
272_6327     3
            ..
146_2941     1
146_13761    1
146_10987    1
146_1374     1
433_6237     1
Name: count, Length: 196870, dtype: int64

Hay sucursales que tienen mas de una vez un producto

In [ ]:
bs_inventario[bs_inventario['id_inventario']=='416_12161']

,idSucursal,idProducto,cantidadEnStock,cantidadParaReposicion,reposicionPedida,cantidadPedida,id_inventario
191659,416,12161,3408,1800,NaN,NaN,416_12161
191743,416,12161,336,200,NaN,NaN,416_12161
192023,416,12161,2259,1700,NaN,NaN,416_12161
192036,416,12161,607,200,NaN,NaN,416_12161

Tomaremos el supuesto de que ha ocurrido un error en la empresa que ha provocado la duplicación en mas de una ocasión de ciertos registros de inventario. Para resolver esto, mantendremos únicamente el último registro de cada producto por sucursal, descartando los registros anteriores. Dado que no contamos con fechas que indiquen el momento del registro, utilizaremos el índice como referencia para determinar el orden.

In [ ]:
bs_inventario_ord = bs_inventario.sort_index(ascending=False)
bs_inventario_mod = bs_inventario_ord.drop_duplicates(subset=['idSucursal', 'idProducto'], keep='first')

In [ ]:
bs_inventario_mod['id_inventario'].value_counts()

id_inventario
433_6237    1
145_6677    1
145_6451    1
145_7168    1
145_1360    1
           ..
289_3424    1
289_3708    1
289_768     1
289_6771    1
1_12168     1
Name: count, Length: 196870, dtype: int64

Cada combinación de idSucursal y idProducto está una sola vez.

In [ ]:
bs_inventario_mod.info()

<class 'pandas.core.frame.DataFrame'>
Index: 196870 entries, 199999 to 0
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idSucursal              196870 non-null  int64
 1   idProducto              196870 non-null  int64
 2   cantidadEnStock         196870 non-null  int64
 3   cantidadParaReposicion  196870 non-null  int64
 4   reposicionPedida        7863 non-null    float64
 5   cantidadPedida          5956 non-null    float64
 6   id_inventario           196870 non-null  object
dtypes: float64(2), int64(4), object(1)
memory usage: 12.0+ MB

In [ ]:
bs_inventario_mod.head()

,idSucursal,idProducto,cantidadEnStock,cantidadParaReposicion,reposicionPedida,cantidadPedida,id_inventario
199999,433,6237,3850,1000,NaN,NaN,433_6237
199998,433,601,2340,700,NaN,NaN,433_601
199997,433,8228,455,300,NaN,NaN,433_8228
199996,433,6771,3205,3000,NaN,NaN,433_6771
199995,433,2661,551,100,NaN,NaN,433_2661

###Campo cantidadEnStock

In [ ]:
bs_inventario_mod['cantidadEnStock'].describe()

count    196870.000000
mean       1999.735221
std        1153.644217
min           1.000000
25%        1000.000000
50%        2004.000000
75%        2996.750000
max        4000.000000
Name: cantidadEnStock, dtype: float64

La cantidad mínima es 1, no hay cantidades negativas, y la máxima es 4000, no hay indicios de error.

###Campo cantidadParareposicion

In [ ]:
bs_inventario_mod['cantidadParaReposicion'].describe()

count    196870.000000
mean       1065.472439
std         859.462756
min         100.000000
25%         400.000000
50%         800.000000
75%        1600.000000
max        4000.000000
Name: cantidadParaReposicion, dtype: float64

Las cantidades de reposición son mayores a 100 el mínimo, el máximo 4000. No hay indicios de error.

In [ ]:
conteo_cantidades = bs_inventario_mod.groupby('idProducto')['cantidadParaReposicion'].nunique()
productos_con_diferentes_cantidades = conteo_cantidades[conteo_cantidades > 1]
print(productos_con_diferentes_cantidades)

idProducto
1         9
2        15
3        13
4        12
5        12
         ..
14645     8
14646    10
14647    12
14648    10
14649     8
Name: cantidadParaReposicion, Length: 14649, dtype: int64

In [ ]:
bs_inventario_mod[bs_inventario_mod['idProducto']==1]

,idSucursal,idProducto,cantidadEnStock,cantidadParaReposicion,reposicionPedida,cantidadPedida,id_inventario
185440,402,1,3647,1600,NaN,NaN,402_1
149900,325,1,3979,3100,NaN,NaN,325_1
146609,318,1,248,200,NaN,NaN,318_1
136913,297,1,221,100,NaN,NaN,297_1
133792,290,1,3055,2700,NaN,NaN,290_1
121742,264,1,2983,1600,NaN,NaN,264_1
65176,142,1,667,500,NaN,NaN,142_1
64652,140,1,2570,2000,NaN,NaN,140_1
45759,100,1,3640,3200,NaN,NaN,100_1
44594,98,1,775,100,NaN,NaN,98_1
34557,75,1,3761,400,NaN,NaN,75_1

Para un mismo producto, en diferentes sucursales la cantidad para la reposición es diferente.

###Campo reposicionPedida

In [ ]:
bs_inventario_mod['reposicionPedida'].value_counts()

reposicionPedida
1.0    5956
0.0    1907
Name: count, dtype: int64

El valor positivo 1 es el true, el negativo es 0, y el resto es null.

###Campo cantidadPedida

In [ ]:
bs_inventario_mod['cantidadPedida'].value_counts()

cantidadPedida
376.0     20
200.0     15
333.0     15
303.0     15
240.0     14
          ..
2811.0     1
2013.0     1
3933.0     1
2676.0     1
1042.0     1
Name: count, Length: 2476, dtype: int64

In [ ]:
bs_inventario_mod['cantidadPedida'].describe()

count    5956.000000
mean     1215.645735
std      1202.916040
min       102.000000
25%       363.000000
50%       742.000000
75%      1716.250000
max      7850.000000
Name: cantidadPedida, dtype: float64

La cantidad de reposiciones pedidas coincide con el importe de reposicionPedida positivas. No hay indicios de error.

##Formas Normales

Como la cantidad de Reposición no depende solo del producto, sino de cada sucursal también, es decir la columna depende de la id_inventario, por lo que se estaría aplicando las 3FN.
El resto de las columnas también dependen de la columna id_inventario, se siguen aplicando las 3FN

###Subtabla 1

In [ ]:
bs_inventario_mod.columns

Index(['idSucursal', 'idProducto', 'cantidadEnStock', 'cantidadParaReposicion',
       'reposicionPedida', 'cantidadPedida', 'id_inventario'],
      dtype='object')

In [ ]:
bs_inventario_mod_1 = bs_inventario_mod[['idSucursal', 'idProducto', 'cantidadEnStock', 'cantidadParaReposicion', 'id_inventario']]

bs_inventario_mod_1

,idSucursal,idProducto,cantidadEnStock,cantidadParaReposicion,id_inventario
199999,433,6237,3850,1000,433_6237
199998,433,601,2340,700,433_601
199997,433,8228,455,300,433_8228
199996,433,6771,3205,3000,433_6771
199995,433,2661,551,100,433_2661
...,...,...,...,...,...
4,1,8191,570,200,1_8191
3,1,12093,2116,100,1_12093
2,1,12938,1652,1400,1_12938
1,1,5320,2074,1500,1_5320
0,1,12168,819,500,1_12168

In [ ]:
bs_inventario_mod_1 = bs_inventario_mod_1.reindex(['id_inventario', 'idProducto', 'idSucursal', 'cantidadEnStock', 'cantidadParaReposicion'], axis=1)
bs_inventario_mod_1 = bs_inventario_mod_1.reset_index(drop=True)
bs_inventario_mod_1

,id_inventario,idProducto,idSucursal,cantidadEnStock,cantidadParaReposicion
0,433_6237,6237,433,3850,1000
1,433_601,601,433,2340,700
2,433_8228,8228,433,455,300
3,433_6771,6771,433,3205,3000
4,433_2661,2661,433,551,100
...,...,...,...,...,...
196865,1_8191,8191,1,570,200
196866,1_12093,12093,1,2116,100
196867,1_12938,12938,1,1652,1400
196868,1_5320,5320,1,2074,1500
196869,1_12168,12168,1,819,500

###Subtabla 3

In [ ]:
bs_inventario_mod_2 =  bs_inventario_mod[['id_inventario', 'cantidadPedida', 'reposicionPedida']]
bs_inventario_mod_2

       id_inventario  cantidadPedida  reposicionPedida
199999      433_6237             NaN               NaN
199998       433_601             NaN               NaN
199997      433_8228             NaN               NaN
199996      433_6771             NaN               NaN
199995      433_2661             NaN               NaN
...              ...             ...               ...
4             1_8191             NaN               NaN
3            1_12093             NaN               NaN
2            1_12938             NaN               NaN
1             1_5320             NaN               NaN
0            1_12168             NaN               NaN

[196870 rows x 3 columns]

In [ ]:
bs_inventario_mod_2 = bs_inventario_mod_2.assign(id_repo=pd.factorize(bs_inventario_mod_2['reposicionPedida'], sort=True)[0])
bs_inventario_mod_2['id_repo'] = bs_inventario_mod_2['id_repo']+1
bs_inventario_mod_2.head()

       id_inventario  cantidadPedida  reposicionPedida  id_repo
199999      433_6237             NaN               NaN        0
199998       433_601             NaN               NaN        0
199997      433_8228             NaN               NaN        0
199996      433_6771             NaN               NaN        0
199995      433_2661             NaN               NaN        0

In [ ]:
bs_inventario_mod_3 = bs_inventario_mod_2[['id_repo', 'reposicionPedida']].drop_duplicates(subset = 'id_repo', keep='last')
bs_inventario_mod_3 = bs_inventario_mod_3.reset_index(drop=True)
bs_inventario_mod_3

   id_repo  reposicionPedida
0        1               0.0
1        2               1.0
2        0               NaN

###Subtabla 2

In [ ]:
bs_inventario_mod_2 = bs_inventario_mod_2.drop(columns='reposicionPedida')
bs_inventario_mod_2 = bs_inventario_mod_2.reindex(['id_inventario', 'id_repo', 'cantidadPedida'], axis=1)
bs_inventario_mod_2 = bs_inventario_mod_2.reset_index(drop=True)
bs_inventario_mod_2

       id_inventario  id_repo  cantidadPedida
0           433_6237        0             NaN
1            433_601        0             NaN
2           433_8228        0             NaN
3           433_6771        0             NaN
4           433_2661        0             NaN
...              ...      ...             ...
196865        1_8191        0             NaN
196866       1_12093        0             NaN
196867       1_12938        0             NaN
196868        1_5320        0             NaN
196869       1_12168        0             NaN

[196870 rows x 3 columns]

##Carga a CSV

In [ ]:
bs_inventario_mod_1.to_csv('bs_inventario_mod_1.csv', index=False)
bs_inventario_mod_2.to_csv('bs_inventario_mod_2.csv', index=False)
bs_inventario_mod_3.to_csv('bs_inventario_mod_3.csv', index=False)

#Tabla Maestro Clientes:

In [ ]:
bs_maestro_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25189 entries, 0 to 25188
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   idCliente        25189 non-null  int64
 1   fechaAlta        25189 non-null  datetime64[ns]
 2   fechaNacimiento  25189 non-null  datetime64[ns]
 3   genero           25189 non-null  object
 4   nombre           25189 non-null  object
 5   apellido         25189 non-null  object
 6   email            25189 non-null  object
 7   direccion        25186 non-null  object
 8   ciudad           25187 non-null  object
 9   referencia       16343 non-null  object
 10  provincia        25187 non-null  object
 11  fechaBaja        0 non-null      float64
 12  estado           0 non-null      float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(8)
memory usage: 2.5+ MB

##Importar tabla

In [ ]:
bs_maestro_clientes = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='Maestro CLIENTES')
bs_maestro_clientes.shape

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell H13533 is marked as a date but the serial value 19942527 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

(25189, 13)

In [ ]:
bs_maestro_clientes.head()

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado
0,1,2000-01-01,1950-12-24,femenino,Elise,Ferreira,elise.ferreira@gmail.com,3 De February 0434,Santiago del Estero,402 Referencia: Entrando por Av del Roble....C...,Santiago del Estero,NaN,NaN
1,2,2000-01-01,1970-04-05,masculino,Lucas,Arévalo,lucas.arevalo@gmail.com,rivadavia 667,San Isidro,6 Entre: maipu y primera junta,Buenos Aires,NaN,NaN
2,3,2000-01-01,1962-05-27,masculino,Pablo,Choque,pablo.choque@gmail.com,Lacarra 1940,Castelar,NaN,Buenos Aires,NaN,NaN
3,4,2000-01-02,1952-12-16,masculino,Julio,Santa Cruz,julio.santa_cruz@gmail.com,Industria 815,Azul,NaN,Buenos Aires,NaN,NaN
4,5,2000-01-02,1990-06-01,femenino,Savannah,Guzmán,savannah.guzman@gmail.com,rafael nuñez 257,Arroyito,"Referencia: Porton De Rejas Negro En Cochera, ...",Córdoba,NaN,NaN

In [ ]:
bs_maestro_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25189 entries, 0 to 25188
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   idCliente        25189 non-null  int64
 1   fechaAlta        25189 non-null  datetime64[ns]
 2   fechaNacimiento  25189 non-null  datetime64[ns]
 3   genero           25189 non-null  object
 4   nombre           25189 non-null  object
 5   apellido         25189 non-null  object
 6   email            25189 non-null  object
 7   direccion        25186 non-null  object
 8   ciudad           25187 non-null  object
 9   referencia       16343 non-null  object
 10  provincia        25187 non-null  object
 11  fechaBaja        0 non-null      float64
 12  estado           0 non-null      float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(8)
memory usage: 2.5+ MB

##Control tabla

###Campo idCliente

In [ ]:
bs_maestro_clientes['idCliente'].value_counts()

idCliente
1        1
16802    1
16800    1
16799    1
16798    1
        ..
8395     1
8394     1
8393     1
8392     1
25189    1
Name: count, Length: 25189, dtype: int64

No hay repetidos, puede ser el PK

In [ ]:
bs_maestro_clientes['idCliente'].describe()

count    25189.000000
mean     12595.000000
std       7271.582301
min          1.000000
25%       6298.000000
50%      12595.000000
75%      18892.000000
max      25189.000000
Name: idCliente, dtype: float64

###Campo fechaAlta

In [ ]:
bs_maestro_clientes['fechaAlta'].value_counts()

fechaAlta
2020-04-04    13
2020-05-01    13
2020-03-20    12
2020-04-17    11
2020-03-31    11
              ..
2015-09-26     1
2002-09-22     1
2017-11-25     1
2013-09-03     1
2020-11-18     1
Name: count, Length: 8036, dtype: int64

In [ ]:
años = bs_maestro_clientes['fechaAlta'].dt.year
años.value_counts()

fechaAlta
2020    1437
2019    1142
2013    1139
2005    1122
2009    1112
2008    1099
2006    1098
2021    1093
2015    1086
2014    1086
2007    1082
2016    1081
2017    1073
2004    1072
2011    1071
2010    1047
2018    1044
2012    1039
2022    1037
2003    1017
2000     996
2001     995
2002     981
2023     240
Name: count, dtype: int64

No hay evidencia de errores en las fechas, los años son del rango razonable de alta de clientes.

###Campo fechaNacimiento

In [ ]:
bs_maestro_clientes['fechaNacimiento'].value_counts()

fechaNacimiento
1961-12-31    6
1933-02-11    6
1942-03-16    6
1976-12-01    6
1977-01-20    6
             ..
1957-03-30    1
1948-09-10    1
1996-02-16    1
1940-05-22    1
1958-05-07    1
Name: count, Length: 16620, dtype: int64

In [ ]:
años = bs_maestro_clientes['fechaNacimiento'].dt.year
años.value_counts()

fechaNacimiento
1996    369
1988    368
1933    367
1994    366
1967    365
       ...
1961    298
1969    298
1998    295
1944    290
1965    282
Name: count, Length: 76, dtype: int64

In [ ]:
años.describe()

count    25189.000000
mean      1967.636945
std         21.966836
min       1930.000000
25%       1949.000000
50%       1968.000000
75%       1987.000000
max       2005.000000
Name: fechaNacimiento, dtype: float64

El cliente mayor es de 1930, y el mas chico de 2005. Son fechas razonables para clientes que se dieron de alta entre el 2000 y 2020. La consistencia que habría que analizar es si hay clientes que se dieron de alta previo a la fecha de nacimiento. Vamos a calcular la diferencia en años entre fecha de alta y de nacimiento.

In [ ]:
bs_maestro_clientes_b = bs_maestro_clientes

In [ ]:
bs_maestro_clientes_b['año_alta'] = bs_maestro_clientes_b['fechaAlta'].dt.year
bs_maestro_clientes_b['año_nac'] = bs_maestro_clientes_b['fechaNacimiento'].dt.year
bs_maestro_clientes_b['dif_años'] = bs_maestro_clientes_b['año_alta'] - bs_maestro_clientes_b['año_nac']

In [ ]:
bs_maestro_clientes_b['dif_años'].describe()

count    25189.000000
mean        43.714915
std         22.765439
min          0.000000
25%         24.000000
50%         43.000000
75%         63.000000
max         93.000000
Name: dif_años, dtype: float64

In [ ]:
bs_maestro_clientes_b[bs_maestro_clientes_b['dif_años']==0]

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
475,476,2000-06-27,2000-06-22,femenino,Zulema,Almendras,zulema.almendras@gmail.com,Ayolas 2747,Sarandí,Entre: Cucha Cucha y Escalada,Buenos Aires,NaN,NaN,2000,2000,0
503,504,2000-07-08,2000-03-26,masculino,Renato,Cusi,renato.cusi@gmail.com,Ruta5 km7 barrio 20 vivienda casa 2,Misiones,Referencia: casa amarilla,Misiones,NaN,NaN,2000,2000,0
560,561,2000-07-29,2000-03-30,femenino,Sofia,Grasso,sofia.grasso@gmail.com,Las Frutillas 414,Villa La Angostura,NaN,Neuquén,NaN,NaN,2000,2000,0
730,731,2000-09-29,2000-08-19,femenino,Alina,Llanos,alina.llanos@gmail.com,Avenida Crisologo larralde 2250,Los Alamos,"Torre C, 7B Referencia: 4",Buenos Aires,NaN,NaN,2000,2000,0
848,849,2000-11-10,2000-09-09,masculino,Alex,Smith,alex.smith@gmail.com,Luis Saenz Peña 153,Congreso,Referencia: Estamos De 10 A 18 Hs.Sabados De 1...,Capital Federal,NaN,NaN,2000,2000,0
860,861,2000-11-12,2000-06-18,masculino,Juan David,Garcia,juan_david.garcia@gmail.com,carlos pellegrini 489,Gualeguay,Entre: intendente gianello y misiones,Entre Ríos,NaN,NaN,2000,2000,0
895,896,2000-11-26,2000-10-13,femenino,Anisa,Almada,anisa.almada@gmail.com,Boulevard Mariano Moreno 123,Paraná,Referencia: Negocio Logistica Dh Entre: Urquiz...,Entre Ríos,NaN,NaN,2000,2000,0
903,904,2000-11-28,2000-01-09,masculino,Luis Miguel,Ferrara,luis_miguel.ferrara@gmail.com,15 De Noviembre De 1889 1771,Parque Patricios,2 Entre: solis y entre rios,Capital Federal,NaN,NaN,2000,2000,0
975,976,2000-12-25,2000-11-10,femenino,Amara,Silvestri,amara.silvestri@gmail.com,Martin Fierro 420,Gualeguay,Referencia: Av colon 3098,Entre Ríos,NaN,NaN,2000,2000,0
990,991,2000-12-30,2000-12-23,femenino,Isabel,Del Valle,isabel.del_valle@gmail.com,Azopardo 8150,Santa Fe,NaN,Santa Fe,NaN,NaN,2000,2000,0
1583,1584,2001-08-09,2001-06-12,masculino,Sergio,Poma,sergio.poma@gmail.com,comandamte torres 711,San Rafael,0 Referencia: es una casa con tela por fuera E...,Mendoza,NaN,NaN,2001,2001,0
1629,1630,2001-08-26,2001-06-27,femenino,Betiana,Villca,betiana.villca@gmail.com,Emilio Civit 415,San Rafael,Referencia: Papelería dos hermanos Entre: Vice...,Mendoza,NaN,NaN,2001,2001,0
1690,1691,2001-09-19,2001-04-15,femenino,Elara,Flores,elara.flores@gmail.com,Av La Plata 1511,Boedo,NaN,Capital Federal,NaN,NaN,2001,2001,0
1782,1783,2001-10-25,2001-05-09,masculino,Iván,Gálvez,ivan.galvez@gmail.com,Avenida Presidente Peron 120,Alberti,A Referencia: TOCAR PUERTA NEGRA 76A ENTRE 5 D...,Buenos Aires,NaN,NaN,2001,2001,0
1823,1824,2001-11-07,2001-08-06,masculino,Leonardo,Pizarro,leonardo.pizarro@gmail.com,Manzana J lote 30 SN,Santiago del Estero,NaN,Santiago del Estero,NaN,NaN,2001,2001,0
1855,1856,2001-11-17,2001-09-08,femenino,Anika,Rocabado,anika.rocabado@gmail.com,Echeverría 3102,Belgrano,Referencia: Kiosco De Diarios Y Revistas .Hora...,Capital Federal,NaN,NaN,2001,2001,0
1931,1932,2001-12-08,2001-04-11,masculino,Nicola,Torres,nicola.torres@gmail.com,Sarmiento 171 3315 LEANDRO N. ALEM Argentina SN,Misiones,Referencia: Casa de color melón con zaguán bla...,Misiones,NaN,NaN,2001,2001,0
2197,2198,2002-03-13,2002-01-12,femenino,Matilde,Ortiz,matilde.ortiz@gmail.com,16bis 167,Victorica,Referencia: Plan Plurianual Barrio De Las 60 C...,La Pampa,NaN,NaN,2002,2002,0
2207,2208,2002-03-17,2002-03-03,femenino,Isabella,Ybarra,isabella.ybarra@gmail.com,padre serrano 5781,Misiones,Referencia: junto a dulcería Paola Entre: av. ...,Misiones,NaN,NaN,2002,2002,0
2592,2593,2002-08-11,2002-06-18,femenino,Kira,Quispe,kira.quispe@gmail.com,Esquíu 3127,Santa Fe,"Referencia: Frente a torre telmex, en veterina...",Santa Fe,NaN,NaN,2002,2002,0
2630,2631,2002-08-28,2002-04-17,femenino,Lara,Conti,lara.conti@gmail.com,Garibaldi 1390,Glew,"Referencia: Dentro Del Barrio Santa Ana, Se In...",Buenos Aires,NaN,NaN,2002,2002,0
2657,2658,2002-09-05,2002-08-09,femenino,Brisa,Vera,brisa.vera@gmail.com,Lavalle 1930,Corrientes,NaN,Corrientes,NaN,NaN,2002,2002,0
2822,2823,2002-11-09,2002-05-27,masculino,François,Espinoza,françois.espinoza@gmail.com,Joaquín soto SN,Puerto Madryb,1812 Referencia: Alfondo ay una tienda 3 casas...,Chubut,NaN,NaN,2002,2002,0
2832,2833,2002-11-10,2002-07-15,masculino,Ignacio,Izquierdo,ignacio.izquierdo@gmail.com,Calle 76 732,Mar del Tuyú,NaN,Buenos Aires,NaN,NaN,2002,2002,0
2843,2844,2002-11-15,2002-01-18,masculino,Jerry,Greco,jerry.greco@gmail.com,Boulogne Sur Mer 1006,Godoy Cruz,NaN,Mendoza,NaN,NaN,2002,2002,0
2935,2936,2002-12-19,2002-09-10,masculino,Mateo,Urquiza,mateo.urquiza@gmail.com,Yehuin 361,Rio Grande,NaN,Tierra del Fuego,NaN,NaN,2002,2002,0
3261,3262,2003-04-11,2003-02-25,femenino,Yara,Salazar,yara.salazar@gmail.com,Av. Solis este 583,Santiago del Estero,Referencia: casa con rejas verdes y una Ford l...,Santiago del Estero,NaN,NaN,2003,2003,0
3264,3265,2003-04-11,2003-03-02,masculino,Luigi,Peralta,luigi.peralta@gmail.com,Mariano Moreno SN,Misiones,NaN,Misiones,NaN,NaN,2003,2003,0
3420,3421,2003-06-04,2003-01-03,masculino,Mateus,Callisaya,mateus.callisaya@gmail.com,Avenida homero jauregui SN,Misiones,NaN,Misiones,NaN,NaN,2003,2003,0
3448,3449,2003-06-16,2003-01-11,masculino,Marcelo,Carbone,marcelo.carbone@gmail.com,Urquiza 141,Lastenia.el Mirador Lastenia,Referencia: Casa Con Ladrillos A La Vista Hay ...,Tucumán,NaN,NaN,2003,2003,0
3708,3709,2003-09-18,2003-04-06,masculino,Diego,Huayta,diego.huayta@gmail.com,La Plata 1091,Santiago del Estero,NaN,Santiago del Estero,NaN,NaN,2003,2003,0
3794,3795,2003-10-14,2003-04-28,femenino,Lior,Pérez,lior.perez@gmail.com,catamarca 3420,Santa Fe,local Referencia: Local rojo SABA horario de 9...,Santa Fe,NaN,NaN,2003,2003,0
3796,3797,2003-10-15,2003-02-15,masculino,Charles,Jaramillo,charles.jaramillo@gmail.com,Catamarca 1600,Yerba Buena,Entre: La Paz Y San Luis,Tucumán,NaN,NaN,2003,2003,0
3846,3847,2003-11-01,2003-06-25,masculino,Omar,Colombo,omar.colombo@gmail.com,Intendente Peña 715 715,Villa María Córdoba,NaN,Córdoba,NaN,NaN,2003,2003,0
3859,3860,2003-11-07,2003-06-15,femenino,Brenda,Silvestri,brenda.silvestri@gmail.com,Av. Zeballos 2538,Castelar,Referencia: A la izquierda de Ave. el Santuario,Buenos Aires,NaN,NaN,2003,2003,0
3871,3872,2003-11-11,2003-07-10,femenino,Ariana,Hall,ariana.hall@gmail.com,Peña 2595,Recoleta,NaN,Capital Federal,NaN,NaN,2003,2003,0
3981,3982,2003-12-28,2003-05-15,masculino,José Manuel,Villanueva,jose_manuel.villanueva@gmail.com,Balcarce 395,Santiago del Estero,Referencia: entrega después de 4 PM puerta neg...,Santiago del Estero,NaN,NaN,2003,2003,0
4305,4306,2004-04-14,2004-01-29,masculino,Nicolás,Rocabado,nicolas.rocabado@gmail.com,Moreno 1252,Santiago del Estero,"Referencia: negocio de dulces típicos, dos loc...",Santiago del Estero,NaN,NaN,2004,2004,0
4765,4766,2004-09-17,2004-02-04,femenino,Elisa,López,elisa.lopez@gmail.com,Magallanes 625,Santiago del Estero,32 Referencia: Enfrente de la tienda del ISSST...,Santiago del Estero,NaN,NaN,2004,2004,0
4777,4778,2004-09-20,2004-04-17,femenino,Javiera,Vega,javiera.vega@gmail.com,Marcelo T De Alvear 3230,Jose Clemente Paz,NaN,Buenos Aires,NaN,NaN,2004,2004,0
4870,4871,2004-10-29,2004-10-08,masculino,Juan Ignacio,Hernández,juan_ignacio.hernandez@gmail.com,Alberti 816,Santa Fe,NaN,Santa Fe,NaN,NaN,2004,2004,0
4880,4881,2004-11-02,2004-02-06,femenino,Laura,Solano,laura.solano@gmail.com,Pachi Gorriti 1825,Salta,NaN,Salta,NaN,NaN,2004,2004,0
4897,4898,2004-11-06,2004-11-03,femenino,Maya,Castillo,maya.castillo@gmail.com,Pehuenches 711,Neuquén,Referencia: Rejas Blancas Entre: Luis Beltran ...,Neuquén,NaN,NaN,2004,2004,0
4955,4956,2004-11-28,2004-04-26,femenino,Agustina,Soto,agustina.soto@gmail.com,Montiel 2668,Mataderos,casa 5,Capital Federal,NaN,NaN,2004,2004,0
4966,4967,2004-11-30,2004-09-12,masculino,Santiago,Ortega,santiago.ortega@gmail.com,Agrelo 580,Llavallol,Referencia: Hacer Fc A Fundasmoto SA\n30-71413...,Buenos Aires,NaN,NaN,2004,2004,0
5426,5427,2005-04-29,2005-01-16,femenino,Vivian,Espíndola,vivian.espindola@gmail.com,Honorio Pueyrredón 559,Caballito,SN Referencia: Casa de dos plantas la segunda ...,Capital Federal,NaN,NaN,2005,2005,0
5517,5518,2005-05-28,2005-01-14,femenino,Laura,Sanabria,laura.sanabria@gmail.com,Pje. Marquito chacra 30,Misiones,NaN,Misiones,NaN,NaN,2005,2005,0
5562,5563,2005-06-13,2005-01-19,masculino,Salvador,Ponce,salvador.ponce@gmail.com,24 De September 1544,Concepción,NaN,Tucumán,NaN,NaN,2005,2005,0
5572,5573,2005-06-16,2005-04-04,femenino,Gimena,Aguilar,gimena.aguilar@gmail.com,Avda. San Martin 312,Misiones,Referencia: casa color azul con blanco Entre: ...,Córdoba,NaN,NaN,2005,2005,0
5685,5686,2005-07-25,2005-03-25,femenino,Seraphina,Roberts,seraphina.roberts@gmail.com,Beck Bernard 7950,Santa Fe,26 Referencia: es una casa verde en una unidad...,Santa Fe,NaN,NaN,2005,2005,0
5769,5770,2005-08-19,2005-04-30,femenino,Julián,Gaitán,julian.gaitan@gmail.com,General Lavalle 615,San Fernando,Referencia: Domicilio laboral de 9 a 17hs,Buenos Aires,NaN,NaN,2005,2005,0
5849,5850,2005-09-17,2005-03-10,femenino,Laura,Cáceres,laura.caceres@gmail.com,Laprida 340,San Miguel de Tucuman,NaN,Tucumán,NaN,NaN,2005,2005,0
5976,5977,2005-10-27,2005-09-13,femenino,Marina,Rinaldi,marina.rinaldi@gmail.com,Alvar Nuñez 410,Monte Grande,Entre: Rebizo y García Fernández - 410,Buenos Aires,NaN,NaN,2005,2005,0
6049,6050,2005-11-19,2005-05-29,masculino,Luis,Ferrara,luis.ferrara@gmail.com,Juan domingoPerón 22,Misiones,NaN,Misiones,NaN,NaN,2005,2005,0
6090,6091,2005-12-01,2005-04-08,femenino,Noemi,Pagano,noemi.pagano@gmail.com,av corrientes 2330,Balvanera,Referencia: en lavados ultra cerca de la palap...,Capital Federal,NaN,NaN,2005,2005,0
6132,6133,2005-12-14,2005-04-24,femenino,Lila,Romero,lila.romero@gmail.com,Av. La Plata 2369,Boedo,Referencia: Pintureria Entre: Cnel. Martiniand...,Capital Federal,NaN,NaN,2005,2005,0

Trabajaremos bajo el supuesto que la fechaNacimiento es la fecha de alta de la sociedad del cliente, y no de nacimiento del mismo.

###Campo genero

In [ ]:
bs_maestro_clientes['genero'].value_counts()

genero
femenino             13534
masculino            11609
prefiere no decir       30
indefinido              16
Name: count, dtype: int64

In [ ]:
bs_maestro_clientes[bs_maestro_clientes['genero']=="indefinido"]

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
36,37,2000-01-16,1973-10-10,indefinido,Ariana,Rossi,ariana.rossi@gmail.com,ADE STREET 32,Misiones,NaN,Misiones,NaN,NaN,2000,1973,27
3435,3436,2003-06-09,1955-11-01,indefinido,Zoya,Cordero,zoya.cordero@gmail.com,Victoriano Montes 2455,MAR DEL PLATA SUR,NaN,Buenos Aires,NaN,NaN,2003,1955,48
5101,5102,2005-01-16,1982-12-27,indefinido,Victoria,Gálvez,victoria.galvez@gmail.com,AvMartinez 28,Misiones,NaN,Misiones,NaN,NaN,2005,1982,23
6048,6049,2005-11-19,2002-04-25,indefinido,Martín,Rivero,martin.rivero@gmail.com,Dhdhdhduf SN,Misiones,NaN,Misiones,NaN,NaN,2005,2002,3
7122,7123,2006-11-05,1977-11-16,indefinido,Manuela,Guerra,manuela.guerra@gmail.com,Pasaje 551,Liniers,NaN,Capital Federal,NaN,NaN,2006,1977,29
9704,9705,2009-03-25,1955-03-06,indefinido,Gianna,Rivero,gianna.rivero@gmail.com,Misiones SN,Misiones,NaN,Misiones,NaN,NaN,2009,1955,54
11143,11144,2010-07-21,1987-10-25,indefinido,Elena,Lara,elena.lara@gmail.com,300 viv. j1 dto 12,Misiones,NaN,Misiones,NaN,NaN,2010,1987,23
11304,11305,2010-09-09,1978-08-09,indefinido,Ernesto,Contreras,ernesto.contreras@gmail.com,Los pibes 3,Misiones,NaN,Misiones,NaN,NaN,2010,1978,32
11899,11900,2011-04-05,1936-09-03,indefinido,Melina,Mitchell,melina.mitchell@gmail.com,Rio de la plata 392,Misiones,NaN,Misiones,NaN,NaN,2011,1936,75
13639,13640,2012-11-25,1970-03-14,indefinido,Ximena,Lucero,ximena.lucero@gmail.com,Avenida punta Borja 431,Comodoro Rivadavia,NaN,Chubut,NaN,NaN,2012,1970,42
14033,14034,2013-04-11,1993-10-10,indefinido,Nyah,Ferretti,nyah.ferretti@gmail.com,Puerto Deseado 95,Misiones,NaN,Misiones,NaN,NaN,2013,1993,20
15999,16000,2015-01-11,1990-10-18,indefinido,Aria,Poma,aria.poma@gmail.com,Mxico 524,Misiones,NaN,Misiones,NaN,NaN,2015,1990,25
17783,17784,2016-09-03,2003-05-12,indefinido,Alexa,Solano,alexa.solano@gmail.com,Calle 92303 SN,Misiones,NaN,Misiones,NaN,NaN,2016,2003,13
20354,20355,2019-01-31,1964-11-19,indefinido,Leonardo,Rivas,leonardo.rivas@gmail.com,Coronel Warnes 1666,Lanús,NaN,Buenos Aires,NaN,NaN,2019,1964,55
21211,21212,2019-11-04,1952-02-02,indefinido,Brenda,Téllez,brenda.tellez@gmail.com,147y170 8456,Misiones,NaN,Misiones,NaN,NaN,2019,1952,67
24477,24478,2022-07-12,1967-03-10,indefinido,Alejandro,Prado,alejandro.prado@gmail.com,San Martin 3257,Misiones,NaN,Misiones,NaN,NaN,2022,1967,55

###Campo nombre

In [ ]:
bs_maestro_clientes['nombre'].value_counts()

nombre
Lucas       288
Rafael      282
Leonardo    243
Daniel      202
Carlos      167
           ...
Samantha     11
Meera        11
Carlotta     10
Aline        10
Elia         10
Name: count, Length: 722, dtype: int64

In [ ]:
ord = bs_maestro_clientes.loc[bs_maestro_clientes['nombre'].str.len().sort_values(ascending=False).index]

ord

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
17492,17493,2016-06-01,1959-11-08,masculino,Carlos Alejandro,Gutiérrez,carlos_alejandro.gutierrez@gmail.com,Pasaje julio Aramburu 3173,Salta,NaN,Salta,NaN,NaN,2016,1959,57
5097,5098,2005-01-16,1974-01-01,masculino,Miguel Alejandro,Costa,miguel_alejandro.costa@gmail.com,Hns.Dimitri 33,Santiago del Estero,Referencia: sobre la principal pasa iglesia el...,Santiago del Estero,NaN,NaN,2005,1974,31
16031,16032,2015-01-19,1987-10-19,masculino,Miguel Alejandro,Medina,miguel_alejandro.medina@gmail.com,Vidal 1949 1949,Belgrano,21 Referencia: 21,Capital Federal,NaN,NaN,2015,1987,28
9852,9853,2009-05-18,1935-04-29,masculino,Miguel Alejandro,Quispe,miguel_alejandro.quispe@gmail.com,domingo palacios SN,Santiago del Estero,NaN,Santiago del Estero,NaN,NaN,2009,1935,74
7265,7266,2006-12-27,1971-08-25,masculino,Carlos Alejandro,Cordero,carlos_alejandro.cordero@gmail.com,Oncativo 815,Santiago del Estero,Referencia: Porton rojo,Santiago del Estero,NaN,NaN,2006,1971,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14255,14256,2013-06-19,1970-11-26,femenino,Eva,Márquez,eva.marquez@gmail.com,Avenida Virgen De Guadalupe SN,Santiago del Estero,NaN,Santiago del Estero,NaN,NaN,2013,1970,43
6712,6713,2006-06-30,1972-01-14,femenino,Zoe,Choque,zoe.choque@gmail.com,Jose Maria Zuviria 1572,Santa Fe,NaN,Santa Fe,NaN,NaN,2006,1972,34
17393,17394,2016-04-28,1974-01-31,femenino,Mia,Caruso,mia.caruso@gmail.com,Santa Rosa 4039,Florida Oeste,"Referencia: Portón dorado 2 piso, entregar a p...",Buenos Aires,NaN,NaN,2016,1974,42
13169,13170,2012-06-15,1955-08-22,femenino,Zia,Fariña,zia.fariña@gmail.com,Domingo Faustino Sarmiento SN,Misiones,4 Referencia: 9am a 5pm lunes a viernes Entre:...,Misiones,NaN,NaN,2012,1955,57
10782,10783,2010-03-13,1962-07-13,femenino,Eva,Carbone,eva.carbone@gmail.com,Barrio C.N.E.A. - 9 de Julio SN,Plottier,Casa 41 Referencia: Casa 41 Entre: Otto Seidel...,Neuquén,NaN,NaN,2010,1962,48

Los nombres de máximo largo no tienen indicios de error.

###Campo apellido

In [ ]:
ord_2 = bs_maestro_clientes.loc[bs_maestro_clientes['apellido'].str.len().sort_values(ascending=False).index]
ord_2

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
21759,21760,2020-04-15,1938-11-18,masculino,Arturo,Montenegro,arturo.montenegro@gmail.com,Villa palacios 18,Salta,NaN,Salta,NaN,NaN,2020,1938,82
5707,5708,2005-07-30,1983-05-29,masculino,Julien,Pellegrini,julien.pellegrini@gmail.com,Vicepresidente Adolfo Alsina 61,Longchamps,NaN,Buenos Aires,NaN,NaN,2005,1983,22
12589,12590,2011-11-26,1943-05-06,masculino,Kevin,Villanueva,kevin.villanueva@gmail.com,PINAR DEL NORTE 2507,San Luis,"6 Referencia: es casa grande, esta al pie de c...",San Luis,NaN,NaN,2011,1943,68
18276,18277,2017-02-22,1943-05-31,masculino,Alessandro,Pellegrino,alessandro.pellegrino@gmail.com,Roca Norte 486,Santiago del Estero,Referencia: portón café hay un luminoso de Tel...,Santiago del Estero,NaN,NaN,2017,1943,74
1366,1367,2001-05-20,1945-11-20,masculino,Eduardo,De Angelis,eduardo.de_angelis@gmail.com,Maza 972,Dorrego,NaN,Mendoza,NaN,NaN,2001,1945,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12159,12160,2011-07-03,1952-12-30,femenino,Bianca,Lee,bianca.lee@gmail.com,Callejon Juan Pablo Torres 42,San Martin de los Andes,NaN,Neuquén,NaN,NaN,2011,1952,59
13425,13426,2012-09-13,1948-03-11,femenino,Jade,Lee,jade.lee@gmail.com,Garcia Merou 5454,Gregorio de Laferrere,1 Referencia: Reportarse con el guardia de seg...,Buenos Aires,NaN,NaN,2012,1948,64
17081,17082,2016-01-12,1942-07-05,masculino,José Andrés,Lee,jose_andres.lee@gmail.com,Montevideo 6127,Rosario,5A Referencia: BODEGA EN PARQUE INDUSTRIAL E...,Santa Fe,NaN,NaN,2016,1942,74
24597,24598,2022-08-25,1955-12-08,femenino,Rosalie,Lee,rosalie.lee@gmail.com,Ejército de los andes SN,Santiago del Estero,Referencia: Sobre rancho Santa María \nEn el p...,Santiago del Estero,NaN,NaN,2022,1955,67
4972,4973,2004-12-01,1940-06-30,femenino,Anisa,Lee,anisa.lee@gmail.com,maguna de russo 88,Santiago del Estero,NaN,Santiago del Estero,NaN,NaN,2004,1940,64

Los apellidos tampoco tienen indicios de error.

###Campo email

In [ ]:
bs_maestro_clientes['email'].value_counts()

email
rafael.rodriguez@gmail.com     7
lucas.gutierrez@gmail.com      6
rafael.mamani@gmail.com        6
juan_pablo.rios@gmail.com      5
lucas.olivares@gmail.com       5
                              ..
silvana.gonzales@gmail.com     1
belinda.morales@gmail.com      1
lorenzo.bellini@gmail.com      1
fernando.paredes@gmail.com     1
alexandre.rinaldi@gmail.com    1
Name: count, Length: 22787, dtype: int64

Los mails no aparentan tener error, si puede llamar la antención que haya diferentes clientes con el mismo mail.

In [ ]:
bs_maestro_clientes[bs_maestro_clientes['email']=="rafael.rodriguez@gmail.com"]

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
1705,1706,2001-09-24,1988-12-23,masculino,Rafael,Rodríguez,rafael.rodriguez@gmail.com,Medrano 67,Misiones,NaN,Misiones,NaN,NaN,2001,1988,13
8562,8563,2008-03-09,1966-03-05,masculino,Rafael,Rodríguez,rafael.rodriguez@gmail.com,Radio Urquiza SN,Salta,NaN,Salta,NaN,NaN,2008,1966,42
19963,19964,2018-09-25,1951-10-12,masculino,Rafael,Rodríguez,rafael.rodriguez@gmail.com,Alsina Oeste 434,Santiago del Estero,Referencia: De tacos el chilango 2 calles adel...,Santiago del Estero,NaN,NaN,2018,1951,67
20940,20941,2019-08-14,1981-06-23,masculino,Rafael,Rodríguez,rafael.rodriguez@gmail.com,Del tridente 1127,Pinamar,NaN,Buenos Aires,NaN,NaN,2019,1981,38
21677,21678,2020-04-01,1941-03-29,masculino,Rafael,Rodríguez,rafael.rodriguez@gmail.com,JUNIN 1336,Recoleta,LOCAL Referencia: LOCAL Entre: JUNCAL y FRENCH,Capital Federal,NaN,NaN,2020,1941,79
22576,22577,2020-10-18,1981-02-27,masculino,Rafael,Rodriguez,rafael.rodriguez@gmail.com,Gonzalez Larrosa SN,Cipolletti,30 Referencia: 30,Río Negro,NaN,NaN,2020,1981,39
24388,24389,2022-06-13,2005-11-23,masculino,Rafael,Rodríguez,rafael.rodriguez@gmail.com,Manuel Ugarte 2393,Belgrano,"Referencia: localidad la puerta, en contra esq...",Capital Federal,NaN,NaN,2022,2005,17

Se llaman de la misma forma y viven en distintos lugares, distinto año de nacimiento, no será utilizado el email para el análisis que se realice.

In [ ]:
ord_3 = bs_maestro_clientes.loc[bs_maestro_clientes['email'].str.len().sort_values(ascending=False).index]
ord_3

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
5189,5190,2005-02-11,1995-08-03,masculino,Miguel Alejandro,Valenzuela,miguel_alejandro.valenzuela@gmail.com,Croce 2912,Mar del Plata,NaN,Buenos Aires,NaN,NaN,2005,1995,10
25153,25154,2023-02-27,1951-06-03,masculino,Miguel Alejandro,Quinteros,miguel_alejandro.quinteros@gmail.com,17 2376,General Pico,NaN,La Pampa,NaN,NaN,2023,1951,72
17092,17093,2016-01-15,1987-04-19,masculino,Carlos Alejandro,Hernandez,carlos_alejandro.hernandez@gmail.com,Rodríguez 195,De La Garma,NaN,Buenos Aires,NaN,NaN,2016,1987,29
4127,4128,2004-02-15,1969-07-14,masculino,Miguel Alejandro,Fernández,miguel_alejandro.fernandez@gmail.com,emilio la marca 1050,General Pacheco,casa Referencia: casa Entre: cu y o,Buenos Aires,NaN,NaN,2004,1969,35
17492,17493,2016-06-01,1959-11-08,masculino,Carlos Alejandro,Gutiérrez,carlos_alejandro.gutierrez@gmail.com,Pasaje julio Aramburu 3173,Salta,NaN,Salta,NaN,NaN,2016,1959,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15963,15964,2015-01-02,1973-01-07,femenino,Noa,Ruiz,noa.ruiz@gmail.com,Av Santa Fe 1171,Recoleta,NaN,Capital Federal,NaN,NaN,2015,1973,42
13425,13426,2012-09-13,1948-03-11,femenino,Jade,Lee,jade.lee@gmail.com,Garcia Merou 5454,Gregorio de Laferrere,1 Referencia: Reportarse con el guardia de seg...,Buenos Aires,NaN,NaN,2012,1948,64
22914,22915,2021-01-30,1998-02-07,femenino,Zola,Lee,zola.lee@gmail.com,General López 3902,Santa Fe,NaN,Santa Fe,NaN,NaN,2021,1998,23
1708,1709,2001-09-25,1999-01-19,femenino,Zoe,Soto,zoe.soto@gmail.com,Marano 885,América,NaN,Buenos Aires,NaN,NaN,2001,1999,2
5846,5847,2005-09-17,1980-01-09,femenino,Zia,Ríos,zia.rios@gmail.com,Cano 208,Rawson,Referencia: Pastelería Diana. 11:00 a 18:00 hr...,San Juan,NaN,NaN,2005,1980,25

Los mails mas largos no incluyen información de otra columna ni erronea.

###Campo dirección

In [ ]:
bs_maestro_clientes['direccion'].value_counts()

direccion
Misiones SN             64
gascon SN               25
Alvear 489              15
Hiplito Irigoyen 329    12
Piso 8 SN               12
                        ..
Alem 803                 1
Trole 522                1
jorge newbery 2967       1
Luis Ressio 2480         1
Inmigrante 1854          1
Name: count, Length: 24004, dtype: int64

Vamos a estandarizar aplicandole minúsculas a todas las direcciones.

In [ ]:
no_text = bs_maestro_clientes[~bs_maestro_clientes['direccion'].apply(lambda x: isinstance(x, str))]
no_text

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
402,403,2000-05-31,1999-01-03,femenino,Emma,Medina,emma.medina@gmail.com,2026-05-25 00:00:00,Salta,NaN,Salta,NaN,NaN,2000,1999,1
455,456,2000-06-18,1934-08-23,femenino,Anais,Copa,anais.copa@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,2000,1934,66
531,532,2000-07-16,1943-06-21,femenino,Sofía,Briones,sofia.briones@gmail.com,2240-02-27 00:00:00,Santa Fe,Entre: Aguirre Zabala y Legna,Santa Fe,NaN,NaN,2000,1943,57
822,823,2000-10-31,1990-09-19,masculino,Emiliano,Gentile,emiliano.gentile@gmail.com,1949-08-28 00:00:00,Monteros,Referencia:,Tucumán,NaN,NaN,2000,1990,10
1060,1061,2001-01-22,1937-09-01,masculino,Zayn,Marino,zayn.marino@gmail.com,3340-05-25 00:00:00,Santa Fe,Referencia: Empresa prolimsa,Santa Fe,NaN,NaN,2001,1937,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24767,24768,2022-11-03,2001-05-06,masculino,Carlos Javier,Cabrera,carlos_javier.cabrera@gmail.com,2007-08-23 00:00:00,Ledesma,NaN,Jujuy,NaN,NaN,2022,2001,21
24896,24897,2022-12-11,1949-10-02,femenino,Lara,Benedetti,lara.benedetti@gmail.com,2264-01-04 00:00:00,Santa Fe,Referencia: es azul un piso hay una motociclet...,Santa Fe,NaN,NaN,2022,1949,73
24960,24961,2023-01-04,1937-10-13,femenino,Yanira,Copa,yanira.copa@gmail.com,2816-07-09 00:00:00,Santa Fe,NaN,Santa Fe,NaN,NaN,2023,1937,86
24982,24983,2023-01-10,1954-09-26,masculino,Alejandro,Salinas,alejandro.salinas@gmail.com,2681-09-11 00:00:00,Núñez,Referencia: no funciona el timbre. golpear la ...,Capital Federal,NaN,NaN,2023,1954,69
25085,25086,2023-02-08,2000-09-24,masculino,Alexandre,Alvarado,alexandre.alvarado@gmail.com,1990-02-20 00:00:00,Salta,NaN,Salta,NaN,NaN,2023,2000,23

Hay varias direcciones que son fecha y hora, vamos a estandarizarlas y estas quedaran como NaN

In [ ]:
bs_maestro_clientes['direccion'] =  bs_maestro_clientes['direccion'].str.lower()

In [ ]:
bs_maestro_clientes[bs_maestro_clientes['direccion'].isna()]

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
402,403,2000-05-31,1999-01-03,femenino,Emma,Medina,emma.medina@gmail.com,NaN,Salta,NaN,Salta,NaN,NaN,2000,1999,1
455,456,2000-06-18,1934-08-23,femenino,Anais,Copa,anais.copa@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,2000,1934,66
531,532,2000-07-16,1943-06-21,femenino,Sofía,Briones,sofia.briones@gmail.com,NaN,Santa Fe,Entre: Aguirre Zabala y Legna,Santa Fe,NaN,NaN,2000,1943,57
822,823,2000-10-31,1990-09-19,masculino,Emiliano,Gentile,emiliano.gentile@gmail.com,NaN,Monteros,Referencia:,Tucumán,NaN,NaN,2000,1990,10
1060,1061,2001-01-22,1937-09-01,masculino,Zayn,Marino,zayn.marino@gmail.com,NaN,Santa Fe,Referencia: Empresa prolimsa,Santa Fe,NaN,NaN,2001,1937,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24767,24768,2022-11-03,2001-05-06,masculino,Carlos Javier,Cabrera,carlos_javier.cabrera@gmail.com,NaN,Ledesma,NaN,Jujuy,NaN,NaN,2022,2001,21
24896,24897,2022-12-11,1949-10-02,femenino,Lara,Benedetti,lara.benedetti@gmail.com,NaN,Santa Fe,Referencia: es azul un piso hay una motociclet...,Santa Fe,NaN,NaN,2022,1949,73
24960,24961,2023-01-04,1937-10-13,femenino,Yanira,Copa,yanira.copa@gmail.com,NaN,Santa Fe,NaN,Santa Fe,NaN,NaN,2023,1937,86
24982,24983,2023-01-10,1954-09-26,masculino,Alejandro,Salinas,alejandro.salinas@gmail.com,NaN,Núñez,Referencia: no funciona el timbre. golpear la ...,Capital Federal,NaN,NaN,2023,1954,69
25085,25086,2023-02-08,2000-09-24,masculino,Alexandre,Alvarado,alexandre.alvarado@gmail.com,NaN,Salta,NaN,Salta,NaN,NaN,2023,2000,23

In [ ]:
bs_maestro_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25189 entries, 0 to 25188
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   idCliente        25189 non-null  int64
 1   fechaAlta        25189 non-null  datetime64[ns]
 2   fechaNacimiento  25189 non-null  datetime64[ns]
 3   genero           25189 non-null  object
 4   nombre           25189 non-null  object
 5   apellido         25189 non-null  object
 6   email            25189 non-null  object
 7   direccion        25014 non-null  object
 8   ciudad           25187 non-null  object
 9   referencia       16343 non-null  object
 10  provincia        25187 non-null  object
 11  fechaBaja        0 non-null      float64
 12  estado           0 non-null      float64
 13  año_alta         25189 non-null  int32
 14  año_nac          25189 non-null  int32
 15  dif_años         25189 non-null  int32
dtypes: datetime64[ns](2), float64(2), int32(3), int64(1), object(8)
memory usage: 2.8+ MB

###Campo ciudad

In [ ]:
bs_maestro_clientes['ciudad'].value_counts()

ciudad
Santiago del Estero       4008
Misiones                  1931
Santa Fe                  1072
Salta                      984
La Rioja                   312
                          ...
Gonzáles Catán               1
Las Lajitas Anta Salta       1
San Juan De La Sierra        1
Loma Verde                   1
san fernando                 1
Name: count, Length: 2968, dtype: int64

In [ ]:
caracteres_defiltro = "[-]"
ciudad_caract = bs_maestro_clientes[bs_maestro_clientes['ciudad'].str.contains(caracteres_defiltro, regex=True, na=False)]
ciudad_caract

,idCliente,fechaAlta,fechaNacimiento,genero,nombre,apellido,email,direccion,ciudad,referencia,provincia,fechaBaja,estado,año_alta,año_nac,dif_años
216,217,2000-03-18,1937-07-11,masculino,Óliver,Huamán,oliver.huaman@gmail.com,mza 204 lote 6 sn,Cordoba - Valle escondido - Santina Norte,Referencia: ...,Córdoba,NaN,NaN,2000,1937,63
466,467,2000-06-24,1936-06-18,femenino,Lara,Alonso,lara.alonso@gmail.com,camino a liebig sn,Villa San José -colon,a6 Referencia: a6 Entre: lucio blanco y experi...,Entre Ríos,NaN,NaN,2000,1936,64
802,803,2000-10-24,1942-12-31,femenino,Ariana,Silva,ariana.silva@gmail.com,ayelén 2694,Vistalba-Luján de Cuyo,NaN,Mendoza,NaN,NaN,2000,1942,58
1071,1072,2001-01-28,1964-05-20,masculino,Paolo,Piras,paolo.piras@gmail.com,av belgrano 624,caba - san telmo,NaN,Capital Federal,NaN,NaN,2001,1964,37
1640,1641,2001-08-30,1988-10-20,masculino,Emilio,Rivas,emilio.rivas@gmail.com,eizaguirre 3926,SAN JUSTO - VILLA CONSTRUCTORA,Referencia: Entrega en tiendita azul Entre: Fr...,Buenos Aires,NaN,NaN,2001,1988,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23610,23611,2021-09-14,1993-06-15,femenino,Maeva,Flores,maeva.flores@gmail.com,berutti 3181,Victoria-San Fernando,Referencia: es en el tercer piso. 2do piso col...,Buenos Aires,NaN,NaN,2021,1993,28
23852,23853,2021-12-08,1989-04-26,femenino,Priscila,Balbuena,priscila.balbuena@gmail.com,av. junín sn,Agustin Roca - Junin,Casa Referencia: Entre Rivadavia y Belgrano. C...,Buenos Aires,NaN,NaN,2021,1989,32
24118,24119,2022-03-10,1949-10-10,femenino,Alba,Paniagua,alba.paniagua@gmail.com,alpatacal 344,Villa Nueva - Guaymallén,Referencia: Saguan Azul Frente A Un Poste De M...,Mendoza,NaN,NaN,2022,1949,73
24364,24365,2022-06-06,1954-03-20,femenino,Sienna,Gálvez,sienna.galvez@gmail.com,ruta 9 km 86 44,Zarate - Barrio Solares del Carmen,Referencia: Barrio Solares Del Carmen. Porteri...,Buenos Aires,NaN,NaN,2022,1954,68
24558,24559,2022-08-08,1956-04-14,masculino,Miguel Ángel,Chávez,miguel_angel.chavez@gmail.com,los alamos 1111,La Calera - La Rufina,Lote 479,Córdoba,NaN,NaN,2022,1956,66

Para dejar la ciudad limpia, vamos a agregar la información adicional del campo a referencia.

In [ ]:
split_columns = bs_maestro_clientes['ciudad'].str.split(r'\s*-\s*', n=1, expand=True)
split_columns[1] = split_columns[1].fillna('')
bs_maestro_clientes['ciudad'] = split_columns[0]
bs_maestro_clientes['referencia'] = bs_maestro_clientes['referencia'].fillna('').astype(str)
split_columns[1] = split_columns[1].astype(str)
bs_maestro_clientes['referencia'] = bs_maestro_clientes['referencia'] + ' ' + split_columns[1]
bs_maestro_clientes['referencia'] = bs_maestro_clientes['referencia'].str.strip()
print(bs_maestro_clientes[['ciudad', 'referencia']])

                    ciudad                                         referencia
0      Santiago del Estero  402 Referencia: Entrando por Av del Roble....C...
1               San Isidro                    6  Entre: maipu y primera junta
2                 Castelar
3                     Azul
4                 Arroyito  Referencia: Porton De Rejas Negro En Cochera, ...
...                    ...                                                ...
25184         san fernando
25185              Palermo                                                 12
25186              Capital               Entre: 25 de mayo y 24 de septiembre
25187             Misiones                               Puerto Rico misiones
25188  Santiago del Estero

[25189 rows x 2 columns]

###Campo provincia

In [ ]:
bs_maestro_clientes['provincia'].value_counts()

provincia
Buenos Aires           7230
Capital Federal        4425
Santiago del Estero    4082
Misiones               2014
Santa Fe               1739
Salta                  1103
Córdoba                 958
Chubut                  630
Mendoza                 398
Entre Ríos              362
La Rioja                358
Neuquén                 278
Tucumán                 247
Corrientes              227
Río Negro               217
San Luis                139
Chaco                   128
Santa Cruz              116
Formosa                 113
San Juan                105
Jujuy                   101
La Pampa                101
Catamarca                88
Tierra del Fuego         19
Entre Ros                 3
Crdoba                    3
Neuqun                    2
Ro Negro                  1
Name: count, dtype: int64

In [ ]:
bs_maestro_clientes['provincia'].value_counts().sort_index()

provincia
Buenos Aires           7230
Capital Federal        4425
Catamarca                88
Chaco                   128
Chubut                  630
Corrientes              227
Crdoba                    3
Córdoba                 958
Entre Ros                 3
Entre Ríos              362
Formosa                 113
Jujuy                   101
La Pampa                101
La Rioja                358
Mendoza                 398
Misiones               2014
Neuqun                    2
Neuquén                 278
Ro Negro                  1
Río Negro               217
Salta                  1103
San Juan                105
San Luis                139
Santa Cruz              116
Santa Fe               1739
Santiago del Estero    4082
Tierra del Fuego         19
Tucumán                 247
Name: count, dtype: int64

Detectamos errores en Entre Rios, Córdoba, Rio Negro y Neuquén. Reemplazaremos por los valores correctos.

In [ ]:
reemplazos = {
    'Ro Negro': 'Río Negro',
    'Entre Ros': 'Entre Ríos',
    'Crdoba': 'Córdoba',
    'Neuqun': 'Neuquén'
}
bs_maestro_clientes['provincia'] = bs_maestro_clientes['provincia'].replace(reemplazos)

In [ ]:
bs_maestro_clientes['provincia'].value_counts().sort_index()

provincia
Buenos Aires           7230
Capital Federal        4425
Catamarca                88
Chaco                   128
Chubut                  630
Corrientes              227
Córdoba                 961
Entre Ríos              365
Formosa                 113
Jujuy                   101
La Pampa                101
La Rioja                358
Mendoza                 398
Misiones               2014
Neuquén                 280
Río Negro               218
Salta                  1103
San Juan                105
San Luis                139
Santa Cruz              116
Santa Fe               1739
Santiago del Estero    4082
Tierra del Fuego         19
Tucumán                 247
Name: count, dtype: int64

##Formas Normales

In [ ]:
bs_maestro_clientes.columns

Index(['idCliente', 'fechaAlta', 'fechaNacimiento', 'genero', 'nombre',
       'apellido', 'email', 'direccion', 'ciudad', 'referencia', 'provincia',
       'fechaBaja', 'estado', 'año_alta', 'año_nac', 'dif_años'],
      dtype='object')

###Subtabla 1

In [ ]:
bs_maestro_clientes_1 = bs_maestro_clientes[['idCliente', 'fechaAlta', 'fechaNacimiento', 'nombre',
       'apellido', 'email', 'fechaBaja', 'estado']]

###Subtabla 3

In [ ]:
bs_maestro_clientes_2 = bs_maestro_clientes[['idCliente', 'genero']]
bs_maestro_clientes_2 = bs_maestro_clientes_2.assign(id_genero=pd.factorize(bs_maestro_clientes_2['genero'], sort=True)[0])
bs_maestro_clientes_2['id_genero'] = bs_maestro_clientes_2['id_genero']+1
bs_maestro_clientes_2

       idCliente     genero  id_genero
0              1   femenino          1
1              2  masculino          3
2              3  masculino          3
3              4  masculino          3
4              5   femenino          1
...          ...        ...        ...
25184      25185  masculino          3
25185      25186  masculino          3
25186      25187  masculino          3
25187      25188  masculino          3
25188      25189  masculino          3

[25189 rows x 3 columns]

In [ ]:
bs_maestro_clientes_3 = bs_maestro_clientes_2[['id_genero','genero']].drop_duplicates(subset='id_genero', keep="last")
bs_maestro_clientes_3 = bs_maestro_clientes_3.sort_values(by=['id_genero'])
bs_maestro_clientes_3 = bs_maestro_clientes_3.reset_index(drop=True)
bs_maestro_clientes_3.head()

   id_genero             genero
0          1           femenino
1          2         indefinido
2          3          masculino
3          4  prefiere no decir

###Subtabla 2

In [ ]:
bs_maestro_clientes_2 = bs_maestro_clientes_2.drop(columns='genero')
bs_maestro_clientes_2.head()

   idCliente  id_genero
0          1          1
1          2          3
2          3          3
3          4          3
4          5          1

In [ ]:
bs_maestro_clientes_4 = bs_maestro_clientes[['idCliente', 'direccion', 'ciudad', 'referencia', 'provincia']]
bs_maestro_clientes_4 = bs_maestro_clientes_4.assign(id_prov=pd.factorize(bs_maestro_clientes_4['provincia'], sort=True)[0])
bs_maestro_clientes_4['id_prov'] = bs_maestro_clientes_4['id_prov']+1
bs_maestro_clientes_4.head()

,idCliente,direccion,ciudad,referencia,provincia,id_prov
0,1,3 de february 0434,Santiago del Estero,402 Referencia: Entrando por Av del Roble....C...,Santiago del Estero,22
1,2,rivadavia 667,San Isidro,6 Entre: maipu y primera junta,Buenos Aires,1
2,3,lacarra 1940,Castelar,,Buenos Aires,1
3,4,industria 815,Azul,,Buenos Aires,1
4,5,rafael nuñez 257,Arroyito,"Referencia: Porton De Rejas Negro En Cochera, ...",Córdoba,7

In [ ]:
bs_maestro_clientes_5 = bs_maestro_clientes_4[['id_prov', 'provincia']].drop_duplicates(subset='id_prov', keep="last")
bs_maestro_clientes_5 = bs_maestro_clientes_5.sort_values(by=['id_prov'])
bs_maestro_clientes_5 = bs_maestro_clientes_5.reset_index(drop=True)
bs_maestro_clientes_5

    id_prov            provincia
0         0                  NaN
1         1         Buenos Aires
2         2      Capital Federal
3         3            Catamarca
4         4                Chaco
5         5               Chubut
6         6           Corrientes
7         7              Córdoba
8         8           Entre Ríos
9         9              Formosa
10       10                Jujuy
11       11             La Pampa
12       12             La Rioja
13       13              Mendoza
14       14             Misiones
15       15              Neuquén
16       16            Río Negro
17       17                Salta
18       18             San Juan
19       19             San Luis
20       20           Santa Cruz
21       21             Santa Fe
22       22  Santiago del Estero
23       23     Tierra del Fuego
24       24              Tucumán

In [ ]:
bs_maestro_clientes_4 = bs_maestro_clientes_4.drop(columns='provincia')
bs_maestro_clientes_4.head()

,idCliente,direccion,ciudad,referencia,id_prov
0,1,3 de february 0434,Santiago del Estero,402 Referencia: Entrando por Av del Roble....C...,22
1,2,rivadavia 667,San Isidro,6 Entre: maipu y primera junta,1
2,3,lacarra 1940,Castelar,,1
3,4,industria 815,Azul,,1
4,5,rafael nuñez 257,Arroyito,"Referencia: Porton De Rejas Negro En Cochera, ...",7

##Carga CSV

In [ ]:
bs_maestro_clientes_1.to_csv('bs_maestro_clientes_1.csv', index=False)
bs_maestro_clientes_2.to_csv('bs_maestro_clientes_2.csv', index=False)
bs_maestro_clientes_3.to_csv('bs_maestro_clientes_3.csv', index=False)
bs_maestro_clientes_4.to_csv('bs_maestro_clientes_4.csv', index=False)
bs_maestro_clientes_5.to_csv('bs_maestro_clientes_5.csv', index=False)

##Creación Base SQL - en servidor

In [ ]:
###SQL para bs_maestro_clientes_1.csv:
CREATE TABLE bs_maestro_clientes_1 (
  idCliente INT,
  fechaAlta VARCHAR(255),
  fechaNacimiento VARCHAR(255),
  nombre VARCHAR(255),
  apellido VARCHAR(255),
  email VARCHAR(255),
  fechaBaja FLOAT,
  estado FLOAT
);

###SQL para bs_maestro_clientes_2.csv:
CREATE TABLE bs_maestro_clientes_2 (
  idCliente INT,
  id_genero INT
);

###SQL para bs_maestro_clientes_3.csv:
CREATE TABLE bs_maestro_clientes_3 (
  id_genero INT,
  genero VARCHAR(255)
);

###SQL para bs_maestro_clientes_4.csv:
CREATE TABLE bs_maestro_clientes_4 (
  idCliente INT,
  direccion VARCHAR(255),
  ciudad VARCHAR(255),
  referencia VARCHAR(255),
  id_prov INT
);

###SQL para bs_maestro_clientes_5.csv:
CREATE TABLE bs_maestro_clientes_5 (
  id_prov INT,
  provincia VARCHAR(255)
);

##Carga SQL

In [ ]:
# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["bs_maestro_clientes_1.csv", "bs_maestro_clientes_2.csv", "bs_maestro_clientes_3.csv", "bs_maestro_clientes_4.csv", "bs_maestro_clientes_5.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")

#Tabla Ordenes:

In [ ]:
bs_ordenes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100072 entries, 0 to 100071
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   idOrden       100072 non-null  int64
 1   montoTotal    100072 non-null  float64
 2   fechaCompra   100072 non-null  datetime64[ns]
 3   idCliente     100072 non-null  int64
 4   idSucursal    100072 non-null  int64
 5   metodoDePago  100072 non-null  object
 6   estado        100072 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 5.3+ MB

##Importar tabla

In [ ]:
bs_ordenes = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='ORDENES')
bs_ordenes.shape

(100072, 7)

In [ ]:
bs_ordenes.head()

,idOrden,montoTotal,fechaCompra,idCliente,idSucursal,metodoDePago,estado
0,28084,3795.57,2002-04-15,1992,13,tarjeta de crédito,concretada
1,84572,1523.69,2002-04-24,1952,2,tarjeta de debito,concretada
2,3337,919.12,2002-08-09,1267,34,tarjeta de debito,concretada
3,24222,930.35,2002-08-19,2443,5,mercadopago,cancelada
4,75,72.27,2002-12-21,139,7,tarjeta de debito,concretada

##Control tabla

###Control idOrden

In [ ]:
bs_ordenes['idOrden'].value_counts()

idOrden
28084    1
72369    1
56279    1
51144    1
49806    1
        ..
68309    1
64481    1
55685    1
41949    1
37012    1
Name: count, Length: 100072, dtype: int64

No hay idOrden repetidas, puede ser el PK de la tabla.

In [ ]:
bs_ordenes['idOrden'].describe()

count    100072.000000
mean      50063.488568
std       28888.462201
min           1.000000
25%       25045.750000
50%       50063.500000
75%       75081.250000
max      100099.000000
Name: idOrden, dtype: float64

Hay 100.072 registros y el número máximo de idOrden de registros es 100.099. Hay una diferencia de 27 movimientos no registrados en la tabla, o registrados pero que fueron borrados. Consideraremos para este trabajo como no significativo los 27 casos faltantes en un universo de 100.072 operaciones.

In [ ]:
bs_ordenes[bs_ordenes['idOrden']==23668]

,idOrden,montoTotal,fechaCompra,idCliente,idSucursal,metodoDePago,estado
27903,23668,790.16,2011-07-14,12095,229,efectivo,concretada

###Control montoTotal

In [ ]:
bs_ordenes['montoTotal'].describe()

count    1.000720e+05
mean     1.157924e+05
std      3.850456e+05
min      2.000000e+00
25%      1.162898e+03
50%      2.036220e+03
75%      5.097885e+03
max      2.958344e+06
Name: montoTotal, dtype: float64

###Campo fechaCompra

In [ ]:
años = bs_ordenes['fechaCompra'].dt.year
años.value_counts()

fechaCompra
2014    9052
2012    8875
2013    8671
2011    7318
2015    6863
2016    6663
2010    6650
2009    6548
2020    5852
2008    5112
2021    4426
2019    4284
2017    4223
2018    4218
2022    4103
2007    3450
2006    1615
2023    1305
2005     588
2004     215
2003      36
2002       5
Name: count, dtype: int64

In [ ]:
años.describe()

count    100072.000000
mean       2013.984591
std           4.417378
min        2002.000000
25%        2011.000000
50%        2014.000000
75%        2017.000000
max        2023.000000
Name: fechaCompra, dtype: float64

Los años son razonables de operación, no hay indicio de error en fechas de compras.

###Campo idCliente

In [ ]:
bs_ordenes['idCliente'].value_counts()

idCliente
13258    15
24460    12
10506    12
17306    12
5997     12
         ..
20339     1
7838      1
20379     1
20342     1
25165     1
Name: count, Length: 24706, dtype: int64

In [ ]:
bs_ordenes['idCliente'].describe()

count    100072.000000
mean      12591.476617
std        7277.891429
min           1.000000
25%        6291.000000
50%       12579.000000
75%       18892.000000
max       25189.000000
Name: idCliente, dtype: float64

Coincide el idCliente mayor, 25189 con el maestro clientes.

###Campo Sucursal

In [ ]:
bs_ordenes['idSucursal'].describe()

count    100072.000000
mean        216.902930
std         125.038092
min           1.000000
25%         109.000000
50%         217.000000
75%         325.000000
max         433.000000
Name: idSucursal, dtype: float64

In [ ]:
bs_ordenes['idSucursal'].nunique()

433

El id máximo de sucursal también coincide con el máximo de idSucursal del Maestro sucursales.

###Campo metodoDePago

In [ ]:
bs_ordenes['metodoDePago'].value_counts()

metodoDePago
efectivo              34701
tarjeta de debito     31238
tarjeta de crédito    31109
transferencia          2229
mercadopago             795
Name: count, dtype: int64

Los medios de pagos estan tipificados, no hay indicios de error.

###Campo estado

In [ ]:
bs_ordenes['estado'].value_counts()

estado
concretada         55784
tuvo_devolucion    20151
cancelada          16113
rechazada           8018
en_proceso             6
Name: count, dtype: int64

Los estados están tipificados, no hay indicios de error.

##Formas Normales

In [ ]:
bs_ordenes.columns

Index(['idOrden', 'montoTotal', 'fechaCompra', 'idCliente', 'idSucursal',
       'metodoDePago', 'estado'],
      dtype='object')

In [ ]:
bs_ordenes_1 = bs_ordenes[['idOrden', 'montoTotal', 'fechaCompra', 'idCliente', 'idSucursal']]
bs_ordenes_1.head()

   idOrden  montoTotal fechaCompra  idCliente  idSucursal
0    28084     3795.57  2002-04-15       1992          13
1    84572     1523.69  2002-04-24       1952           2
2     3337      919.12  2002-08-09       1267          34
3    24222      930.35  2002-08-19       2443           5
4       75       72.27  2002-12-21        139           7

In [ ]:
bs_ordenes_2 = bs_ordenes[['idOrden', 'metodoDePago']]
bs_ordenes_2 = bs_ordenes_2.assign(id_metpago=pd.factorize(bs_ordenes_2['metodoDePago'], sort=True)[0])
bs_ordenes_2['id_metpago'] = bs_ordenes_2['id_metpago']+1
bs_ordenes_2.head()

   idOrden        metodoDePago  id_metpago
0    28084  tarjeta de crédito           3
1    84572   tarjeta de debito           4
2     3337   tarjeta de debito           4
3    24222         mercadopago           2
4       75   tarjeta de debito           4

In [ ]:
bs_ordenes_3 = bs_ordenes_2[['id_metpago','metodoDePago']].drop_duplicates(subset='id_metpago', keep="last")
bs_ordenes_3 = bs_ordenes_3.sort_values(by=['id_metpago'])
bs_ordenes_3 = bs_ordenes_3.reset_index(drop=True)
bs_ordenes_3

   id_metpago        metodoDePago
0           1            efectivo
1           2         mercadopago
2           3  tarjeta de crédito
3           4   tarjeta de debito
4           5       transferencia

In [ ]:
bs_ordenes_2 = bs_ordenes_2.drop('metodoDePago', axis=1)
bs_ordenes_2

        idOrden  id_metpago
0         28084           3
1         84572           4
2          3337           4
3         24222           2
4            75           4
...         ...         ...
100067    94001           4
100068    21130           1
100069    45228           2
100070    92618           1
100071    37012           4

[100072 rows x 2 columns]

In [ ]:
bs_ordenes_4 = bs_ordenes[['idOrden','estado']]
bs_ordenes_4 = bs_ordenes_4.assign(id_estado=pd.factorize(bs_ordenes_4['estado'], sort=True)[0])
bs_ordenes_4['id_estado'] = bs_ordenes_4['id_estado']+1
bs_ordenes_4

        idOrden           estado  id_estado
0         28084       concretada          2
1         84572       concretada          2
2          3337       concretada          2
3         24222        cancelada          1
4            75       concretada          2
...         ...              ...        ...
100067    94001  tuvo_devolucion          5
100068    21130       en_proceso          3
100069    45228       concretada          2
100070    92618  tuvo_devolucion          5
100071    37012       en_proceso          3

[100072 rows x 3 columns]

In [ ]:
bs_ordenes_5 = bs_ordenes_4[['id_estado','estado']].drop_duplicates(subset='id_estado', keep="last")
bs_ordenes_5 = bs_ordenes_5.sort_values(by=['id_estado'])
bs_ordenes_5 = bs_ordenes_5.reset_index(drop=True)
bs_ordenes_5

   id_estado           estado
0          1        cancelada
1          2       concretada
2          3       en_proceso
3          4        rechazada
4          5  tuvo_devolucion

In [ ]:
bs_ordenes_4 = bs_ordenes_4.drop('estado', axis=1)
bs_ordenes_4.head()

   idOrden  id_estado
0    28084          2
1    84572          2
2     3337          2
3    24222          1
4       75          2

##Carga CSV

In [ ]:
bs_ordenes_1.to_csv('bs_ordenes_1.csv', index=False)
bs_ordenes_2.to_csv('bs_ordenes_2.csv', index=False)
bs_ordenes_3.to_csv('bs_ordenes_3.csv', index=False)
bs_ordenes_4.to_csv('bs_ordenes_4.csv', index=False)
bs_ordenes_5.to_csv('bs_ordenes_5.csv', index=False)

##Creación Base SQL - en servidor

In [ ]:
###SQL para bs_ordenes_1.csv:
CREATE TABLE bs_ordenes_1 (
  idOrden INT,
  montoTotal FLOAT,
  fechaCompra VARCHAR(255),
  idCliente INT,
  idSucursal INT
);

###SQL para bs_ordenes_2.csv:
CREATE TABLE bs_ordenes_2 (
  idOrden INT,
  id_metpago INT
);

###SQL para bs_ordenes_3.csv:
CREATE TABLE bs_ordenes_3 (
  id_metpago INT,
  metodoDePago VARCHAR(255)
);

###SQL para bs_ordenes_4.csv:
CREATE TABLE bs_ordenes_4 (
  idOrden INT,
  id_estado INT
);

###SQL para bs_ordenes_5.csv:
CREATE TABLE bs_ordenes_5 (
  id_estado INT,
  estado VARCHAR(255)
);

##Carga SQL

In [ ]:
# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["bs_ordenes_1.csv", "bs_ordenes_2.csv", "bs_ordenes_3.csv", "bs_ordenes_4.csv", "bs_ordenes_5.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")

#Tabla Ordenes detalle:

In [ ]:
bs_ordenes_det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400019 entries, 0 to 400018
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idOrden         400019 non-null  int64
 1   idProducto      400019 non-null  int64
 2   cantidad        400019 non-null  int64
 3   precioUnitario  400019 non-null  float64
 4   precio          400019 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 15.3 MB

##Importar tabla

In [ ]:
bs_ordenes_det = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='ORDENES_DETALLE')
bs_ordenes_det.shape

(400019, 5)

In [ ]:
bs_ordenes_det.head()

   idOrden  idProducto  cantidad  precioUnitario    precio
0        1         755        10           32.09    320.90
1        1        6688         2           90.45    180.90
2        2       11458         3           39.59    118.77
3        3        3963         9          185.00   1665.00
4        4         705        12          999.00  11988.00

##Control tabla

###Campo idOrden

In [ ]:
bs_ordenes_det['idOrden'].value_counts()

idOrden
1553     11
74917    10
6120     10
34255     9
4546      9
         ..
24        1
23        1
22        1
69        1
97        1
Name: count, Length: 100072, dtype: int64

In [ ]:
bs_ordenes_det['idOrden'].describe()

count    400019.000000
mean      50105.828436
std       28879.434856
min           1.000000
25%       25101.500000
50%       50118.000000
75%       75095.000000
max      100099.000000
Name: idOrden, dtype: float64

El idOrden máximo es 100.099, igual que la tabla ordenes.

In [ ]:
bs_ordenes_det['idOrden'].nunique()

100072

Y un total de idOrden distintos de 100.072 igual también que la tabla ordenes.

###Campo idProducto

In [ ]:
bs_ordenes_det['idProducto'].value_counts()

idProducto
14703    51
9393     49
471      48
5759     47
10546    46
         ..
13172    11
11939    11
8413     11
13155    10
3648      9
Name: count, Length: 14834, dtype: int64

In [ ]:
bs_ordenes_det['idProducto'].describe()

count    400019.000000
mean       7421.797675
std        4285.388397
min           1.000000
25%        3709.000000
50%        7425.000000
75%       11129.000000
max       14834.000000
Name: idProducto, dtype: float64

El idProducto máximo coincide con el id máximo de la tabla maestro de productos.

###Campo cantidad

In [ ]:
bs_ordenes_det['cantidad'].describe()

count    400019.000000
mean          6.495919
std           3.453485
min           1.000000
25%           3.000000
50%           6.000000
75%          10.000000
max          12.000000
Name: cantidad, dtype: float64

In [ ]:
bs_ordenes_det['cantidad'].value_counts()

cantidad
3     33697
2     33637
6     33546
11    33439
4     33417
8     33326
9     33324
12    33291
10    33289
5     33120
1     33114
7     32819
Name: count, dtype: int64

Las cantidades son todas mayores a 0, y el máximo es 12 productos, lo que es razonable, no hay indicios de errores.

###Campo preciounitario

In [ ]:
bs_ordenes_det['precioUnitario'].value_counts()

precioUnitario
39.59     2672
32.09     2319
199.00    2254
42.79     2243
21.39     2226
          ...
175.99      15
114.39      15
276.00      15
2.49        15
91.80       14
Name: count, Length: 2705, dtype: int64

In [ ]:
bs_ordenes_det['precioUnitario'].describe()

count    400019.000000
mean        108.426421
std         155.105722
min           1.800000
25%          29.000000
50%          55.290000
75%         110.000000
max         999.900000
Name: precioUnitario, dtype: float64

Los precios unitarios no tienen indicios de error en su columna, son razonables, son mayores a 0 y no poseen valores nulos.

###Campo precio

In [ ]:
bs_ordenes_det['precio'].value_counts()

precio
160.50     507
321.00     447
240.75     398
288.90     394
80.25      385
          ...
104.58       1
429.75       1
405.60       1
1112.75      1
346.40       1
Name: count, Length: 24162, dtype: int64

In [ ]:
bs_ordenes_det['precio'].describe()

count    400019.000000
mean        703.089035
std        1194.980202
min           1.800000
25%         139.410000
50%         316.360000
75%         717.200000
max       11998.800000
Name: precio, dtype: float64

In [ ]:
bs_ordenes_det['precio'].nunique()

24162

###Campo id_orden_prod

Crearemos un id único para la tabla en detalle, concatenando el idOrden y idProducto

In [ ]:
bs_ordenes_det['id_ord_prod']= bs_ordenes_det['idOrden'].astype(str) +"_"+ bs_ordenes_det['idProducto'].astype(str)

In [ ]:
bs_ordenes_det

        idOrden  idProducto  cantidad  precioUnitario    precio   id_ord_prod
0             1         755        10           32.09    320.90         1_755
1             1        6688         2           90.45    180.90        1_6688
2             2       11458         3           39.59    118.77       2_11458
3             3        3963         9          185.00   1665.00        3_3963
4             4         705        12          999.00  11988.00         4_705
...         ...         ...       ...             ...       ...           ...
400014   100098        6323        12           25.20    302.40   100098_6323
400015   100099        7938        12          199.00   2388.00   100099_7938
400016   100099        7669         7          255.00   1785.00   100099_7669
400017   100099        7771         6           12.90     77.40   100099_7771
400018   100099       12347         5            8.05     40.25  100099_12347

[400019 rows x 6 columns]

In [ ]:
bs_ordenes_det['id_ord_prod'].value_counts()

id_ord_prod
98252_14362     2
66411_13857     2
14611_9476      2
23668_8207      2
72796_14431     2
               ..
33425_12799     1
33424_2053      1
33424_2668      1
33424_246       1
100099_12347    1
Name: count, Length: 399981, dtype: int64

In [ ]:
bs_ordenes_det[bs_ordenes_det['id_ord_prod']=="23668_8207"]

       idOrden  idProducto  cantidad  precioUnitario  precio id_ord_prod
94281    23668        8207         3           19.99   59.97  23668_8207
94283    23668        8207        11           19.99  219.89  23668_8207

In [ ]:
bs_ordenes_det['calc'] = np.where(bs_ordenes_det['cantidad'] * bs_ordenes_det['precioUnitario'] == bs_ordenes_det['precio'], 'A', 'M')
bs_ordenes_det

,idOrden,idProducto,cantidad,precioUnitario,precio,id_ord_prod,calc
0,1,755,10,32.09,320.90,1_755,A
1,1,6688,2,90.45,180.90,1_6688,A
2,2,11458,3,39.59,118.77,2_11458,A
3,3,3963,9,185.00,1665.00,3_3963,A
4,4,705,12,999.00,11988.00,4_705,A
...,...,...,...,...,...,...,...
400014,100098,6323,12,25.20,302.40,100098_6323,A
400015,100099,7938,12,199.00,2388.00,100099_7938,A
400016,100099,7669,7,255.00,1785.00,100099_7669,A
400017,100099,7771,6,12.90,77.40,100099_7771,A
400018,100099,12347,5,8.05,40.25,100099_12347,A

Los valores de la sumatoria de los productos de una orden, no totalizan el importe de montototal de la tabla ordenes. Para avanzar con el análisis sumaremos las cantidades y volveremos a calcular el precio total.

In [ ]:
bs_ordenes_det_mod = bs_ordenes_det.groupby('id_ord_prod').agg({
    'idOrden': 'last',              # Primer valor de 'idOrden'
    'idProducto': 'last',           # Primer valor de 'idProducto'
    'cantidad': 'sum',               # Sumar la columna 'cantidad'
    'precioUnitario': 'last',       # Primer valor de 'precioUnitario'
    'precio': 'sum',               # Primer valor de 'precio'
    'calc': 'last'                  # Primer valor de 'calc'
}).reset_index()

In [ ]:
bs_ordenes_det[bs_ordenes_det['id_ord_prod']=="23668_8207"]

       idOrden  idProducto  cantidad  precioUnitario  precio id_ord_prod calc
94281    23668        8207         3           19.99   59.97  23668_8207    A
94283    23668        8207        11           19.99  219.89  23668_8207    A

In [ ]:
bs_ordenes_det_mod[bs_ordenes_det_mod['id_ord_prod']=="23668_8207"]

      id_ord_prod  idOrden  idProducto  cantidad  precioUnitario  precio calc
61101  23668_8207    23668        8207        14           19.99  279.86    A

Tomamos como ejemplo la id_ord_prod 23668_8207 son 14 productos a 19.99 valor total 279.86.
Procedemos a revisar si todos las cantidades por precioUnitario es igual al precio.

In [ ]:
bs_ordenes_det_mod['calc'] = np.where((bs_ordenes_det_mod['cantidad'] * bs_ordenes_det_mod['precioUnitario']).round(2) == bs_ordenes_det_mod['precio'].round(2), 'A', 'M')
bs_ordenes_det_mod[bs_ordenes_det_mod['calc']=="M"]

Empty DataFrame
Columns: [id_ord_prod, idOrden, idProducto, cantidad, precioUnitario, precio, calc]
Index: []

No hay diferencia entre el calculo de cantidad x precioUnitario y el precio. Redondeamos en 2 decimales para eliminar error de decimales.

In [ ]:
bs_ordenes_det_mod = bs_ordenes_det_mod.drop(['calc'], axis=1)

In [ ]:
bs_ordenes_det_mod

         id_ord_prod  idOrden  idProducto  cantidad  precioUnitario    precio
0        100000_1576   100000        1576         4           52.45    209.80
1         100000_270   100000         270         2           28.35     56.70
2        100000_4098   100000        4098        12          889.00  10668.00
3        100000_7005   100000        7005        12          699.00   8388.00
4       100001_12172   100001       12172         8           75.90    607.20
...              ...      ...         ...       ...             ...       ...
399976     999_12456      999       12456         1           18.50     18.50
399977     999_14597      999       14597         8           37.35    298.80
399978      999_8828      999        8828         7           39.89    279.23
399979        9_2477        9        2477         8          123.05    984.40
399980        9_8721        9        8721         5          489.00   2445.00

[399981 rows x 6 columns]

In [ ]:
bs_ordenes_det_mod[bs_ordenes_det_mod['id_ord_prod']=="91895_1042"]

       id_ord_prod  idOrden  idProducto  cantidad  precioUnitario  precio
363905  91895_1042    91895        1042         9           39.59  356.31

##Formas Normales

In [ ]:
bs_ordenes_det_mod.columns

Index(['id_ord_prod', 'idOrden', 'idProducto', 'cantidad', 'precioUnitario',
       'precio'],
      dtype='object')

In [ ]:
bs_ordenes_det_mod_1 = bs_ordenes_det_mod[['id_ord_prod', 'idOrden', 'idProducto', 'cantidad', 'precioUnitario', 'precio']]

##Carga CSV

In [ ]:
bs_ordenes_det_mod_1.to_csv('bs_ordenes_det_mod_1.csv', index=False)

##Creación Base SQL - en servidor

In [ ]:
###SQL para bs_ordenes_det_mod_1.csv:
CREATE TABLE bs_ordenes_det_mod_1 (
  id_ord_prod VARCHAR(255),
  idOrden INT,
  idProducto INT,
  cantidad INT,
  precioUnitario FLOAT,
  precio FLOAT
);

##Carga a SQL

In [ ]:
# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["bs_ordenes_det_mod_1.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")

#Tabla Devoluciones:

In [ ]:
bs_devoluciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22171 entries, 0 to 22170
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   idOrden           22171 non-null  int64
 1   idProducto        22171 non-null  int64
 2   cantidadDevuelta  22171 non-null  int64
 3   fechaDevolucion   22171 non-null  datetime64[ns]
 4   motivoDevolucion  22171 non-null  object
 5   resolucion        22171 non-null  object
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 1.0+ MB

##Importar tabla

In [ ]:
bs_devoluciones = pd.read_excel('/content/drive/MyDrive/UBA_diplo2024/Base_Diplo_Datos_Supermercado.xlsx', sheet_name='DEVOLUCIONES')
bs_devoluciones.shape

(22171, 6)

In [ ]:
bs_devoluciones.head()

,idOrden,idProducto,cantidadDevuelta,fechaDevolucion,motivoDevolucion,resolucion
0,100,2757,3,2016-09-24,Producto dañado o defectuoso,Crédito de la tienda
1,100,8813,7,2016-09-28,Producto o tamaño incorrecto,Intercambio por nuevos productos
2,100,10659,1,2016-10-04,Producto dañado o defectuoso,Intercambio por variante
3,116,8421,3,2019-12-08,Producto dañado o defectuoso,Intercambio por nuevos productos
4,119,9756,6,2013-10-08,Producto o tamaño incorrecto,Intercambio por variante

##Control tabla

###Campo idOrden

In [ ]:
bs_devoluciones['idOrden'].value_counts()

idOrden
93474     4
89054     4
90235     4
91834     4
30965     4
         ..
37795     1
37794     1
37793     1
37779     1
100098    1
Name: count, Length: 20151, dtype: int64

In [ ]:
bs_devoluciones['idOrden'].describe()

count     22171.000000
mean      54334.114790
std       30294.378755
min         100.000000
25%       27677.500000
50%       55452.000000
75%       83149.500000
max      100098.000000
Name: idOrden, dtype: float64

En las devoluciones hay mas de un idproducto, los números de idOrden coinciden con los de las otras tablas.

###Campo idProducto

In [ ]:
bs_devoluciones['idProducto'].value_counts()

idProducto
11632    9
2114     8
5624     8
13547    8
6075     8
        ..
6971     1
8043     1
14636    1
13362    1
11592    1
Name: count, Length: 11522, dtype: int64

In [ ]:
bs_devoluciones['idProducto'].describe()

count    22171.000000
mean      7412.300077
std       4297.437540
min          1.000000
25%       3693.500000
50%       7359.000000
75%      11107.500000
max      14833.000000
Name: idProducto, dtype: float64

El número máximo de idProducto esta dentro del rango de los id de productos de la tabla maestro de productos.

### Campo cantidadDevuelta

In [ ]:
bs_devoluciones['cantidadDevuelta'].value_counts()

cantidadDevuelta
1     5743
2     3884
3     2970
4     2352
5     1865
6     1453
7     1265
8      920
9      741
10     508
11     313
12     157
Name: count, dtype: int64

La cantidad minima devuelta es 1, no hay ninguna con 0, y máxima 12, no hay indicios de error.

In [ ]:
bs_devoluciones['cantidadDevuelta'].describe()

count    22171.000000
mean         3.750981
std          2.726424
min          1.000000
25%          1.000000
50%          3.000000
75%          5.000000
max         12.000000
Name: cantidadDevuelta, dtype: float64

El promedio de cantidad devuelta es 3,75. Es razonable siendo que es menor a la cantidad promedio de items comprados.

In [ ]:
bs_devoluciones['fechaDevolucion'].value_counts()

fechaDevolucion
2012-12-22    16
2014-06-17    15
2011-06-02    14
2013-02-01    14
2011-11-10    14
              ..
2017-12-15     1
2022-05-28     1
2010-01-16     1
2006-03-07     1
2007-01-02     1
Name: count, Length: 6027, dtype: int64

In [ ]:
años = bs_devoluciones['fechaDevolucion'].dt.year
años.value_counts()

fechaDevolucion
2014    1990
2012    1965
2013    1921
2011    1627
2015    1538
2016    1480
2009    1472
2010    1445
2020    1275
2008    1120
2019     996
2021     987
2017     954
2018     895
2022     888
2007     786
2006     347
2023     339
2005     115
2004      25
2003       5
2002       1
Name: count, dtype: int64

Los años de las fechas de devolución son razonables. No hay indicios de error.

###Campo motivoDevolucion

In [ ]:
bs_devoluciones['motivoDevolucion'].value_counts()

motivoDevolucion
Cambio de idea o insatisfacción personal    7444
Producto dañado o defectuoso                7396
Producto o tamaño incorrecto                7331
Name: count, dtype: int64

Los motivos de devolución estan tipificados, no hay indicios de error.

### Campo resolucion

In [ ]:
bs_devoluciones['resolucion'].value_counts()

resolucion
Crédito de la tienda                5574
Intercambio por nuevos productos    5569
Reembolso                           5532
Intercambio por variante            5496
Name: count, dtype: int64

Las resoluciones estan tipificadas, no hay indicios de error.

###Campo id_ord_prod

In [ ]:
bs_devoluciones['id_ord_prod']= bs_devoluciones['idOrden'].astype(str) +"_"+ bs_devoluciones['idProducto'].astype(str)
bs_devoluciones

,idOrden,idProducto,cantidadDevuelta,fechaDevolucion,motivoDevolucion,resolucion,id_ord_prod
0,100,2757,3,2016-09-24,Producto dañado o defectuoso,Crédito de la tienda,100_2757
1,100,8813,7,2016-09-28,Producto o tamaño incorrecto,Intercambio por nuevos productos,100_8813
2,100,10659,1,2016-10-04,Producto dañado o defectuoso,Intercambio por variante,100_10659
3,116,8421,3,2019-12-08,Producto dañado o defectuoso,Intercambio por nuevos productos,116_8421
4,119,9756,6,2013-10-08,Producto o tamaño incorrecto,Intercambio por variante,119_9756
...,...,...,...,...,...,...,...
22166,100093,8578,2,2011-04-22,Producto dañado o defectuoso,Intercambio por nuevos productos,100093_8578
22167,100093,11772,6,2011-05-10,Producto o tamaño incorrecto,Reembolso,100093_11772
22168,100094,3232,2,2014-03-19,Producto o tamaño incorrecto,Intercambio por variante,100094_3232
22169,100095,12323,1,2021-01-06,Producto dañado o defectuoso,Intercambio por nuevos productos,100095_12323
22170,100098,14362,6,2016-10-09,Producto o tamaño incorrecto,Intercambio por nuevos productos,100098_14362

In [ ]:
bs_devoluciones['id_ord_prod'].value_counts()

id_ord_prod
91895_1042      2
100_2757        1
73618_7144      1
73671_3028      1
73662_4446      1
               ..
36816_10197     1
36813_8702      1
36801_8825      1
36801_10083     1
100098_14362    1
Name: count, Length: 22170, dtype: int64

In [ ]:
bs_devoluciones[bs_devoluciones['id_ord_prod']=="91895_1042"]

,idOrden,idProducto,cantidadDevuelta,fechaDevolucion,motivoDevolucion,resolucion,id_ord_prod
19104,91895,1042,1,2007-06-02,Producto dañado o defectuoso,Reembolso,91895_1042
19105,91895,1042,1,2007-06-25,Producto o tamaño incorrecto,Intercambio por variante,91895_1042

La orden 91895 tiene el producto 1042 que ha sido registrada la devolución dos veces, nos quedamos con la segunda, debido a que es la posterior, y trabajamos bajo el supuesto que hubo un inconveniente con el reembolso.

In [ ]:
bs_devoluciones = bs_devoluciones.drop(index=19104)

In [ ]:
bs_devoluciones['id_ord_prod'].value_counts()

id_ord_prod
100_2757        1
73610_13880     1
73662_4446      1
73650_822       1
73634_3072      1
               ..
36816_10197     1
36813_8702      1
36801_8825      1
36801_10083     1
100098_14362    1
Name: count, Length: 22170, dtype: int64

De esta forma el id_ord_prod puede ser PK de la tabla.

##Formas Normales

###Subtabla 1

In [ ]:
bs_devoluciones.columns

Index(['idOrden', 'idProducto', 'cantidadDevuelta', 'fechaDevolucion',
       'motivoDevolucion', 'resolucion', 'id_ord_prod'],
      dtype='object')

In [ ]:
bs_devoluciones_1 = bs_devoluciones[['idOrden', 'idProducto', 'cantidadDevuelta', 'fechaDevolucion', 'id_ord_prod']]
bs_devoluciones_1 = bs_devoluciones_1.reindex(['id_ord_prod', 'idOrden', 'idProducto', 'cantidadDevuelta', 'fechaDevolucion'], axis =1)
bs_devoluciones_1

        id_ord_prod  idOrden  idProducto  cantidadDevuelta fechaDevolucion
0          100_2757      100        2757                 3      2016-09-24
1          100_8813      100        8813                 7      2016-09-28
2         100_10659      100       10659                 1      2016-10-04
3          116_8421      116        8421                 3      2019-12-08
4          119_9756      119        9756                 6      2013-10-08
...             ...      ...         ...               ...             ...
22166   100093_8578   100093        8578                 2      2011-04-22
22167  100093_11772   100093       11772                 6      2011-05-10
22168   100094_3232   100094        3232                 2      2014-03-19
22169  100095_12323   100095       12323                 1      2021-01-06
22170  100098_14362   100098       14362                 6      2016-10-09

[22170 rows x 5 columns]

###Subtabla 3

In [ ]:
bs_devoluciones_2 = bs_devoluciones[['id_ord_prod', 'motivoDevolucion']]
bs_devoluciones_2 = bs_devoluciones_2.assign(id_motdev=pd.factorize(bs_devoluciones_2['motivoDevolucion'], sort=True)[0])
bs_devoluciones_2['id_motdev'] = bs_devoluciones_2['id_motdev']+1
bs_devoluciones_2.head()

  id_ord_prod              motivoDevolucion  id_motdev
0    100_2757  Producto dañado o defectuoso          2
1    100_8813  Producto o tamaño incorrecto          3
2   100_10659  Producto dañado o defectuoso          2
3    116_8421  Producto dañado o defectuoso          2
4    119_9756  Producto o tamaño incorrecto          3

In [ ]:
bs_devoluciones_3 = bs_devoluciones_2[['id_motdev', 'motivoDevolucion']].drop_duplicates(subset='id_motdev', keep="last")
bs_devoluciones_3 = bs_devoluciones_3.reset_index(drop=True)
bs_devoluciones_3

   id_motdev                          motivoDevolucion
0          1  Cambio de idea o insatisfacción personal
1          2              Producto dañado o defectuoso
2          3              Producto o tamaño incorrecto

###Subtabla 2

In [ ]:
bs_devoluciones_2 = bs_devoluciones_2.drop('motivoDevolucion', axis=1)
bs_devoluciones_2.head()

  id_ord_prod  id_motdev
0    100_2757          2
1    100_8813          3
2   100_10659          2
3    116_8421          2
4    119_9756          3

###Subtabla 5

In [ ]:
bs_devoluciones_4 = bs_devoluciones[['id_ord_prod', 'resolucion']]
bs_devoluciones_4 = bs_devoluciones_4.assign(id_resol=pd.factorize(bs_devoluciones_4['resolucion'], sort=True)[0])
bs_devoluciones_4['id_resol'] = bs_devoluciones_4['id_resol']+1
bs_devoluciones_4.head()

  id_ord_prod                        resolucion  id_resol
0    100_2757              Crédito de la tienda         1
1    100_8813  Intercambio por nuevos productos         2
2   100_10659          Intercambio por variante         3
3    116_8421  Intercambio por nuevos productos         2
4    119_9756          Intercambio por variante         3

In [ ]:
bs_devoluciones_5 = bs_devoluciones_4[['id_resol', 'resolucion']].drop_duplicates(subset='id_resol', keep="last")
bs_devoluciones_5 = bs_devoluciones_5.sort_values(by='id_resol')
bs_devoluciones_5 = bs_devoluciones_5.reset_index(drop=True)
bs_devoluciones_5

   id_resol                        resolucion
0         1              Crédito de la tienda
1         2  Intercambio por nuevos productos
2         3          Intercambio por variante
3         4                         Reembolso

###Subtabla 4

In [ ]:
bs_devoluciones_4 = bs_devoluciones_4.drop('resolucion', axis=1)
bs_devoluciones_4

        id_ord_prod  id_resol
0          100_2757         1
1          100_8813         2
2         100_10659         3
3          116_8421         2
4          119_9756         3
...             ...       ...
22166   100093_8578         2
22167  100093_11772         4
22168   100094_3232         3
22169  100095_12323         2
22170  100098_14362         2

[22170 rows x 2 columns]

##Carga CSV

In [ ]:
bs_devoluciones_1.to_csv('bs_devoluciones_1.csv', index=False)
bs_devoluciones_2.to_csv('bs_devoluciones_2.csv', index=False)
bs_devoluciones_3.to_csv('bs_devoluciones_3.csv', index=False)
bs_devoluciones_4.to_csv('bs_devoluciones_4.csv', index=False)
bs_devoluciones_5.to_csv('bs_devoluciones_5.csv', index=False)

##Creación Base SQL - en servidor

In [ ]:
###SQL para bs_devoluciones_1.csv:
CREATE TABLE bs_devoluciones_1 (
  id_ord_prod VARCHAR(255),
  idOrden INT,
  idProducto INT,
  cantidadDevuelta INT,
  fechaDevolucion VARCHAR(255)
);

###SQL para bs_devoluciones_2.csv:
CREATE TABLE bs_devoluciones_2 (
  id_ord_prod VARCHAR(255),
  id_motdev INT
);

###SQL para bs_devoluciones_3.csv:
CREATE TABLE bs_devoluciones_3 (
  id_motdev INT,
  motivoDevolucion VARCHAR(255)
);

###SQL para bs_devoluciones_4.csv:
CREATE TABLE bs_devoluciones_4 (
  id_ord_prod VARCHAR(255),
  id_resol INT
);

###SQL para bs_devoluciones_5.csv:
CREATE TABLE bs_devoluciones_5 (
  id_resol INT,
  resolucion VARCHAR(255)
);

##Carga SQL

In [ ]:
# Conexión a la DDBB
from sqlalchemy import create_engine

USERNAME = "root"
PASSWORD = ""
BBDD = "supermercado"
PORT = "3306"  # Puerto por defecto para MySQL
SERVICE = "localhost"

# Lista de archivos CSV
csv_files = ["bs_devoluciones_1.csv", "bs_devoluciones_2.csv", "bs_devoluciones_3.csv", "bs_devoluciones_4.csv", "bs_devoluciones_5.csv"]

if __name__ == "__main__":
    # Creación del motor de conexión
    engine = create_engine(f'mysql+mysqlconnector://{USERNAME}:{PASSWORD}@{SERVICE}:{PORT}/{BBDD}', echo=False)

    # Cargar los CSVs en las tablas
    for csv_file in csv_files:
        table_name = csv_file.split(".")[0]
        df = pd.read_csv(csv_file)
        df.to_sql(table_name, engine, index=False, if_exists='replace')
        print(f"Datos cargados en la tabla {table_name}")